### ISSUE TITLE
Unable to use different symbols in tplot.

### ISSUE THREAD

**Issue by pspathare** [spedas/pyspedas#1008]
I am working on plotting a tplot variable that contains three different energy levels, each with associated errors. I have successfully stored the energy and its corresponding errors in a tplot variable using store_data and applied the necessary plot options. While I am able to plot the error bars, the values I am seeing in the plot are not what I expect(Symbols for each value).

To verify this, I also plotted the data using matplotlib and achieved the correct results (attached below). However, I am encountering issues when plotting with tplot. It seems that there might be some configuration in pyplot.options that I am either overlooking.

Code:
#Using tplot variable
proton_E1 = proton_intensity[1][:,0]
proton_err_E1 = proton_intensity[2][:,0]
pytplot.store_data('pro_inte',data={'x':time,'y':proton_E1,'dy':proton_err_E1})
pytplot.options('pro_inte',opt_dict={'ylog':1,'yrange':[0.001,1000],'linestyle':'dot'})

tplot('pro_inte')

#Using Matplotlib
ax1.errorbar(datetimes_time,proton_E1,proton_err_E1,fmt='^', capsize=0, capthick=0)

Attachments:

Expected plot (generated with matplotlib)

<img width="1186" alt="Screenshot 2024-09-05 at 7 11 43 PM" src="https://github.com/user-attachments/assets/fa54b995-49e9-4470-9dfc-f5203b889122">

Current plot (generated with tplot)
<img width="1152" alt="Screenshot 2024-09-05 at 7 11 58 PM" src="https://github.com/user-attachments/assets/51d221f0-8201-4fed-8a27-4f7c2ee89faa">

I am unable to plot required symbol using tplot. I suspect there might be an undocumented feature or option in pyplot.options that could resolve this issue. Any guidance on configuring error bars correctly for tplot would be appreciated.

**Comment by jameswilburlewis** [comment]
I think the options you're looking for are "marker" (and possibly 'symbols' to turn off the line traces). Could you try:

`pytplot.options('pro_inte',opt_dict={'ylog':1,'yrange':[0.001,1000],'linestyle':'dot', 'marker':'^', 'symbols':True})`

and see if that gets you closer to the desired result?   There's also a 'markersize' option that lets you adjust the symbol size.

There's a notebook "PyTplot_markers_and_symbols", along with others in our pyspedas_examples repo, that may be of interest:

pyspedas_examples repo:
https://github.com/spedas/pyspedas_examples

Google Colab link to markers and symbols example notebook:

https://colab.research.google.com/github/spedas/pyspedas_examples/blob/master/pyspedas_examples/notebooks/PyTplot_markers_and_symbols.ipynb

**Comment by pspathare** [comment]
It did plot the symbols but it is not turning off the line traces.
Here is the image
<img width="1195" alt="Screenshot 2024-09-06 at 9 56 37 AM" src="https://github.com/user-attachments/assets/1c6c4000-97fd-4d87-a550-45106741777e">

**Comment by jameswilburlewis** [comment]
I see!  It looks like the pytplot lineplot routine isn't setting the matplotlib `fmt` argument properly for error bar plots.  That shouldn't be too hard to fix.

**Comment by jameswilburlewis** [comment]
I've just released pytplot-mpl-temp version 2.2.43, which should fix this issue.   But you'll need to use a different set of options than I originally suggested.  Setting 'symbols' to True will create a scatter plot, which won't handle the error bars.  

Instead, to turn off the connecting lines, set 'linestyle' = 'None' (as a string):

`pytplot.options('pro_inte',opt_dict={'ylog':1,'yrange':[0.001,1000],'linestyle':'None', marker':'^'})`

We don't support Matplotlib 'fmt' strings directly, yet, but this is something we'll think about adding in the future.

Please let us know if the new release works for you!

**Comment by pspathare** [comment]
It's working.
Thank you.
