### ISSUE TITLE
warnings.simplefilter("ignore", np.ComplexWarning) is not not working in pyspedas.analysis.twavpol.wavpol

### ISSUE THREAD

**Issue by syogi22** [spedas/pyspedas#1012]
In 
result=pyspedas.analysis.twavpol.wavpol(ct, bx, by, bz, nopfft=3200, steplength=400, bin_freq=5)

line 114 of twavpol a command is there
-- warnings.simplefilter("ignore", np.ComplexWarning) but ComplexWarning is removed after Numpy 2.0.0

But;
Warnings and exceptions present in numpy.exceptions (e.g, ComplexWarning, VisibleDeprecationWarning) are no longer exposed in the main namespace.
https://numpy.org/doc/stable/release/2.0.0-notes.html 

kindly correct it.

**Comment by jameswilburlewis** [comment]
Thanks for letting us know -- we'll get that fix released in the next few days.

**Comment by jameswilburlewis** [comment]
Fixed in pyspedas 1.6.1, just released
