### ISSUE TITLE
Load Data from NASA’s CDAWeb

### ISSUE THREAD

**Issue by tmw233** [spedas/pyspedas#1015]
I'm unable to load data from NASA’s CDAWeb, as when I run

>>> from pyspedas import CDAWeb

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[76], line 1
----> 1 from pyspedas import CDAWeb

ImportError: cannot import name 'CDAWeb' from 'pyspedas' (C:\Users\TW\anaconda3\Lib\site-packages\pyspedas\__init__.py)

I'm only able to use the Interactive CDAWeb Browser.

**Comment by jameswilburlewis** [comment]
Are you using the latest code from the pyspedas github repo?  

We recently renamed the cdagui directory (where CDAWeb was being imported from) to cdagui_tools.  There were also a few other renamings: cotrans->cotrans_tools, and hapi->hapi_tools.    The changes haven't been released yet.

I can't reproduce the issue in my environment using the latest github code:

```

from pyspedas import CDAWeb
Backend MacOSX is interactive backend. Turning interactive mode on.
from pyspedas import version
version()
18-Sep-24 10:08:46: pyspedas version: bleeding edge

```
Is it possible that you did a "git pull" of the latest pyspedas code, but haven't restarted your interactive python shell?  If so, you could still have the old directory names on your python path.   I would suggest quitting your python session, doing another 'git pull' (just in case you happened to update while I was in the middle of renaming things), then start a fresh python session and see if you still have problems importing CDAWeb.

I have a feeling that will fix your environment, but if not, let me know and we'll take a closer look.

**Comment by tmw233** [comment]
Thank you!

Yes, I needed to update the version of Pyspedas I was using. It works great now.

Thanks
