### ISSUE TITLE
pyspedas installation issue with numpy.typing

### ISSUE THREAD

**Issue by bpwrs** [spedas/pyspedas#1069]
After installing pyspedas in a venv and running a simple test file, I receive the error
`ModuleNotFoundError: No module named 'numpy.typing'`

Versions and packages are as follows

```
astropy                       5.3.4
cdflib                        1.3.1
matplotlib                    3.7.2
msgpack                       1.1.0
netCDF4                       1.6.5
numexpr                       2.10.2
numpy                         1.23.2
numpydoc                      1.5.0
pandas                        2.2.3
pyspedas                      1.5.17
pytplot-mpl-temp              2.2.39
scipy                         1.11.3
```

I am also using 
`Python 3.9.20`
due to requirements of the server the venv is on. The package version list is the same as another installation I have where I do not receive the error.

**Comment by bpwrs** [comment]
Solved, odd issue with pyspedas installing different versions under different versions of python

**Comment by bpwrs** [comment]
Solved, odd issue with pyspedas installing different versions under different versions of python

**Comment by jameswilburlewis** [comment]
Glad you figured it out!
