### ISSUE TITLE
ylim does not work for a log axis?

### ISSUE THREAD

**Issue by horit** [spedas/pyspedas#107]
Although this should be asked on the pytplot page, let me ask here as I found (and confirmed) it when plotting THEMIS data. Recently my colleagues and I realized that pytplot.ylim() does not work properly for a tplot variable with ylog=1. Looking into the problem by testing with THEMIS/ESA data, we found: 
- a spectrum-type data with a 2-D "v" array (e.g., (times, 32)  ----> ylim works
- a spectrum-type data with a 1-D "v" array (e.g., (32)  ----> ylim NOT work as expected

Isn't this a bug in pytplot or pyspedas? 

Copied below are the commands that reproduce the above latter case on my environment (macOS 10.14.6, Python 3.9.6, pytplot 1.7.28, pyspedas 1.2.8). 

`import pyspedas
import pytplot
pyspedas.themis.spacecraft.particles.esa.esa( varformat='*peir*')
pytplot.options('thc_peir_en_eflux', 'zlog', 1)
pytplot.options('thc_peir_en_eflux', 'ylog', 1)
element_thc_peir_en_eflux = pytplot.get_data('thc_peir_en_eflux')
thc_peir_flux_test_meta_data = pytplot.get_data('thc_peir_en_eflux', metadata=True)
pytplot.store_data('thc_peir_flux_test', data={'x': element_thc_peir_en_eflux[0],
                                              'y': element_thc_peir_en_eflux[1],
                                              'v': element_thc_peir_en_eflux[2][0]},
                   attr_dict=thc_peir_flux_test_meta_data)
pytplot.options('thc_peir_flux_test', 'zlog', 1)
pytplot.zlim('thc_peir_flux_test', (0.00005)*1.e+6, (500.)*1.e+6)
pytplot.options('thc_peir_flux_test', 'ytitle', 'thc_peir_flux_test')
pytplot.tplot('thc_peir_flux_test')  # plot

pytplot.ylim('thc_peir_flux_test', 1000, 24000)
pytplot.tplot('thc_peir_flux_test')      # plot with a different yrange setting`

**Comment by supervised** [comment]
Thank you for the bug report!

This is a bug in the Qt version of pytplot. I've actually been working on a new version of pytplot that only uses matplotlib to generate the figures, and this issue isn't occuring with that one for me. I've been doing development under the 'matplotlib-backend' branch of the pytplot repo:

https://github.com/MAVENSDC/PyTplot/tree/matplotlib-backend

so you can install it using:

pip install --upgrade https://github.com/MAVENSDC/PyTplot/archive/matplotlib-backend.zip

then you import the tplot function from MPLPlotter:

from pytplot.MPLPlotter.tplot import tplot

Here's a notebook that shows some of the features the new version supports:

https://github.com/MAVENSDC/PyTplot/blob/matplotlib-backend/docs/PyTplot%20examples%20with%20matplotlib.ipynb

Hope this helps!

**Comment by supervised** [comment]
Ah, there are NaNs in the energy table for those data, and the spectrogram code didn't like that; I just checked in a fix. 

Latest version should be working:
![Figure_1](https://user-images.githubusercontent.com/4745136/138139619-beba1152-be30-48d1-9829-b8983da950c4.png)

Thanks again! 
Let me know if you run into any other problems!

**Comment by supervised** [comment]
By the way - the ESA load routine can also be accessed via:

pyspedas.themis.esa( trange=['2007-03-23 00:00:00', '2007-03-24 00:00:00'], ...)

(no need to include the full path - you can simply use pyspedas.mission.instrument())

And I had to change varformat to '*peir*' to get it to actually load some data

**Comment by horit** [comment]
Thanks for the quick fix! It works perfectly and now I can plot data even with an energy table containing NaNs. That's quite useful in plotting some of Arase's particle data, because some of the particle instruments often "skip" a few energy steps and leave NaNs there.
