### ISSUE TITLE
ResourceWarning: unclosed socket zmq.Socket

### ISSUE THREAD

**Issue by StellarRemnants** [spedas/pyspedas#112]
When using pyspedas, the following error regularly appears as a printed message to the console:

```
11-Nov-21 20:04:13: /usr/lib/python3.8/asyncio/base_events.py:654: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
```

When using a spyder terminal, the error is instead 

`11-Nov-21 20:03:59: sys:1: ResourceWarning: unclosed socket <zmq.Socket(zmq.PUSH) at 0x7f3255be4880>`

I'm running Ubuntu 20.04 LTS with the following relevant package versions:
pyspedas 1.2.9
pytplot 1.7.28 (matplotlib backend, also appears with release version)
pyzmq 22.3.0
spyder 5.1.5 (also appears when using ipython or python interpreters)

At present, it doesn't seem to affect module usability, but it is certainly an annoyance.

Full module list attached
[pip3list.txt](https://github.com/spedas/pyspedas/files/7524797/pip3list.txt)
.

**Comment by jameswilburlewis** [comment]
It's been a while since this issue was opened -- I'm not seeing any similar console messages in our automated testing on ubuntu-latest.   Are you still seeing these warnings, or can I go ahead and close the issue?
