### ISSUE TITLE
The coordinates of the magnetopause

### ISSUE THREAD

**Issue by ClDoor** [spedas/pyspedas#114]
Hi. 

Is there any way to obtain the position coordinates of the magnetopause in the  given magnetic field model at a certain moment (especially the section of the magnetopause in a certain coordinate plane)? Thanks a lot!

**Comment by supervised** [comment]
Hello,

Not with PySPEDAS (that I know of), but SpacePy has the Shue et al (1997) magnetopause model:

https://spacepy.github.io/autosummary/spacepy.empiricals.getMagnetopause.html

Hope this helps!
