### ISSUE TITLE
phase space density

### ISSUE THREAD

**Issue by Jujotinas** [spedas/pyspedas#115]
Hello All,

I want to plot velocity distribution function of maven spacecraft.
But I need to convert the differential fluxes into velocity distribution function.
which pyspedas routine should I go with in order to plot VDF.

Regards
Justin

**Comment by supervised** [comment]
Hello,

I don't think we have a general routine for converting fluxes into VDFs, but there is a routine in the MMS module that includes the conversion at:

[pyspedas/mms/particles/mms_convert_flux_units.py](https://github.com/spedas/pyspedas/blob/060dc397e3217b35907e5011ca8afa0a971a7c73/pyspedas/mms/particles/mms_convert_flux_units.py)

Hope this helps!

**Comment by Jujotinas** [comment]
Thanks Spedas/Pyspedas.
I will look into it.
