### ISSUE TITLE
Parker Solar Probe load.py doesn't do fields at 4/cyc or 1min due to pathformat differences

### ISSUE THREAD

**Issue by JeffreyBroll** [spedas/pyspedas#117]
The URL string substitution scheme to access PSP datasets doesn't cover the 1min and 4_per_cycle CDFs
1: their URL pathformat needs to have the %H removed as these are 24H files (cf. e.g. fields/l2/mag_rtn_1min/2018/psp_fld_l2_mag_rtn_1min_20181002_v02.cdf for 1min)
2: the 4/cycle URL has inconsistent filepath and filename 'datatype' so this needs to be done manually (cf. e.g. fields/l2/mag_rtn_4_per_cycle/2018/psp_fld_l2_mag_rtn_4_sa_per_cyc_20181002_v02.cdf)

I have not ensured that this would not break anything else but I have been running [a modified load.py](https://github.com/spedas/pyspedas/files/7670634/psp_slash_load_dot_py.txt) (attached, I hope) that accounts for these shenanigans.  

```
    # original lines 38-40
    if instrument == 'fields':
        pathformat = ...
        file_resolution = 6*3600
```

becomes

```
    if instrument == 'fields':
        # 4_per_cycle and 1min are daily, not 6h like the full resolution 'mag_rtn'
        if datatype=='mag_rtn_1min':
            pathformat = instrument + '/' + level + '/' + datatype + '/%Y/psp_fld_' + level + '_' + datatype + '_%Y%m%d_v??.cdf'
        # 4/cyc uses different 'datatype' strings for directory and file, apparently
        elif datatype=='mag_rtn_4_per_cycle' or datatype=='mag_rtn_4_sa_per_cyc':
            pathformat = instrument + '/' + level + '/mag_rtn_4_per_cycle/%Y/psp_fld_' + level + '_mag_rtn_4_sa_per_cyc_%Y%m%d_v??.cdf'
        else:
            pathformat = instrument + '/' + level + '/' + datatype + '/%Y/psp_fld_' + level + '_' + datatype + '_%Y%m%d%H_v??.cdf'
            file_resolution = 6*3600.
        # something similar should go for mag_sc
```

**Comment by supervised** [comment]
Thanks! should be fixed now for both mag_rtn and mag_sc
