### ISSUE TITLE
maven time stamps

### ISSUE THREAD

**Issue by blburkholder** [spedas/pyspedas#118]
I believe the issue is that the routine reading Maven mag data uses the wrong precision.  This minimum example demonstrates:

```
import pyspedas
import pytplot

sdate = '2019-07-11'
edate = '2019-07-11'

mag_vars = pyspedas.maven.mag(trange=[sdate, edate],datatype='ss')
b1 = pytplot.get_data('OB_B')
```

I want the full rate data so I expect the sampling rate to be about 32 Hz. However if I look at the contents of b1.times this is clearly not the case. The time stamps shown below are in units of seconds, and they increase by 1 every 32 entries, making me suspicious of the precision somewhere.

```
>>> b1.times[0:50]-b1.times[0]
array([0.00000000e+00, 3.09944153e-05, 6.29425049e-05, 9.39369202e-05,
       1.24931335e-04, 1.55925751e-04, 1.70946121e-04, 1.87873840e-04,
       2.18868256e-04, 2.49862671e-04, 2.80857086e-04, 3.13043594e-04,
       3.44038010e-04, 9.99374866e-01, 9.99405861e-01, 9.99437809e-01,
       9.99469042e-01, 9.99500036e-01, 9.99531031e-01, 9.99562979e-01,
       9.99593973e-01, 9.99624968e-01, 9.99655962e-01, 9.99687910e-01,
       9.99718904e-01, 9.99749899e-01, 9.99780893e-01, 9.99812841e-01,
       9.99843836e-01, 9.99858856e-01, 9.99874830e-01, 9.99905825e-01,
       9.99938011e-01, 9.99969006e-01, 1.00000000e+00, 1.00003099e+00,
       1.00006294e+00, 1.00009394e+00, 1.00012493e+00, 1.00015593e+00,
       1.00018787e+00, 1.00021887e+00, 1.00024986e+00, 1.00028086e+00,
       1.00031304e+00, 1.00034404e+00, 1.99937487e+00, 1.99940586e+00,
       1.99943781e+00, 1.99946904e+00])
```
In addition, I did not initially think this was a problem but now I assume that if I can fix some warnings it will solve the issue. When I use the routine `pyspedas.maven.mag()` I always get a bunch of warnings like this

```
10-Dec-21 11:55:49: /home/mysticalbeaver/pyspedas/lib/python3.8/site-packages/pytplot/importers/sts_to_tplot.py:106: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  obs_specific, data={'x': sts_dict['time_unix'], 'y': [np.float(val) for val in sts_dict[var_name]]})
```

As a final note I do not use Anaconda. Not sure if that could be the issue.

**Comment by supervised** [comment]
Thank you for the bug report!

There was a bug in sts_to_tplot.py in pytplot that led to milliseconds being converted to microseconds; I just checked-in a fix:

https://github.com/MAVENSDC/PyTplot/commit/1c2d6c16647d09c4e2e1926432e6d929dd2ea83d

and let Bryan Harter know. I also fixed the issue that led to that DeprecationWarning while I was in there.
