### ISSUE TITLE
Routine for WIND/WAVES experiment 

### ISSUE THREAD

**Issue by MohamedNedal** [spedas/pyspedas#14]
Hi, 
I was wondering if there is a routine in the _WIND mission_ module to import and read data from RAD1 and RAD2 receivers of the WAVES experiment?

**Comment by supervised** [comment]
Hi Mohamed,

I just added one - pyspedas.wind.waves(). 

It looks like there are a few other WIND load routines missing - I'll go ahead and add those too. 

Thanks!
Eric
