### ISSUE TITLE
Setting environment variable after importing pyspedas not updated in  MMS CONFIG

### ISSUE THREAD

**Issue by jmsplank** [spedas/pyspedas#164]
Hi!

I ran into an issue where setting .env variables programmatically after pyspedas is imported does not update the `CONFIG` dict defined in `pyspedas.mms.mms_config`.

I got around this by defining a `_CONFIG` class with a `local_data_dir` property that checks the environment every time it's accessed:

```{python}
#pyspedas/mms/mms_config.py
import os
from typing import Any, Optional


class _CONFIG:
    def __init__(
        self,
        local_data_dir: str = "pydata",
        mirror_data_dir: Optional[str] = None,
        debug_mode: bool = False,
        download_only: bool = False,
        no_download: bool = False,
    ) -> None:
        self._local_data_dir = local_data_dir
        self._mirror_data_dir = mirror_data_dir
        self.debug_mode = debug_mode
        self.download_only = download_only
        self.no_download = no_download

    @property
    def local_data_dir(self) -> str:
        """Checks SPEDAS_DATA_DIR and MMS_DATA_DIR environment
        variables before returning local_data_dir.
        """
        if os.environ.get("SPEDAS_DATA_DIR"):
            self._local_data_dir = os.sep.join([os.environ["SPEDAS_DATA_DIR"], "mms"])

        if os.environ.get("MMS_DATA_DIR"):
            self._local_data_dir = os.environ["MMS_DATA_DIR"]

        return self._local_data_dir

    @property
    def mirror_data_dir(self) -> Optional[str]:
        """Checks MMS_MIRROR_DATA_DIR env var before returning mirror_data_dir"""
        if os.environ.get("MMS_MIRROR_DATA_DIR"):
            CONFIG["mirror_data_dir"] = os.environ["MMS_MIRROR_DATA_DIR"]

    def __getitem__(self, key: str) -> str:
        """Implement getting attributes using square brackets notation.
        e.g. CONFIG['no_download'] works
        """
        return getattr(self, key)

    def __setitem__(self, key: str, value: Any) -> None:
        """Implement setting attribute using square brackets.
        e.g.
        >>> CONFIG['no_download'] = True
        sets CONFIG.no_download

        NOTE: trying to set local_data_dir or mirror_data_dir raises AttributeError
        """
        setattr(self, key, value)

    def to_dict(self) -> dict[str, str]:
        return {
            "local_data_dir": self.local_data_dir,
            "mirror_data_dir": self.mirror_data_dir,
            "debug_mode": self.debug_mode,
            "download_only": self.download_only,
            "no_download": self.no_download,
        }

    def __str__(self):
        return f"{' CONFIG ':-^80}\n" + "\n".join(
            [f"{k} : {v}" for k, v in self.to_dict().items()]
        )


CONFIG = _CONFIG()

```

Happy to submit as pull request if desired.

**Comment by jmsplank** [comment]
Thank for the quick response Eric,

I do want my `local_data_dir` to persist through sessions but to avoid clutter I have variables like these defined in a `.env` which is accessed by an imported setup module.

I'm not sure on how python's import scopes work, if I do `CONFIG['local_data_dir'] = '~/my_new_data_dir'` inside my setup module, will that change always persist or can it be overwritten, e.g. by future imports of `pyspedas.mms.mms_config`?

e.g.
```
# my_setup.py
import os
from dotenv import load_dotenv
from pyspedas.mms.mms_config import CONFIG

load_dotenv('.env')
CONFIG['local_data_dir'] = os.environ['MMS_DATA_DIR']
...
```

is this:
```
import my_setup
from pyspedas.mms.mms_config import CONFIG
print(CONFIG)
```

Always the same as this:
```
from pyspedas.mms.mms_config import CONFIG
import my_setup
print(CONFIG)
```

From testing it looks like they are the same & is a much better solution than a clunky class but accidentally putting GBs of data in the wrong place is obviously something I'd like to avoid!

Thanks a lot,
James

**Comment by supervised** [comment]
> Thank for the quick response Eric,
> 
> I do want my `local_data_dir` to persist through sessions but to avoid clutter I have variables like these defined in a `.env` which is accessed by an imported setup module.
> 
> I'm not sure on how python's import scopes work, if I do `CONFIG['local_data_dir'] = '~/my_new_data_dir'` inside my setup module, will that change always persist or can it be overwritten, e.g. by future imports of `pyspedas.mms.mms_config`?

It shouldn't be overwritten by future imports of `pyspedas.mms.mms_config`



> e.g.
> 
> ```
> # my_setup.py
> import os
> from dotenv import load_dotenv
> from pyspedas.mms.mms_config import CONFIG
> 
> load_dotenv('.env')
> CONFIG['local_data_dir'] = os.environ['MMS_DATA_DIR']
> ...
> ```
> 
> is this:
> 
> ```
> import my_setup
> from pyspedas.mms.mms_config import CONFIG
> print(CONFIG)
> ```
> 
> Always the same as this:
> 
> ```
> from pyspedas.mms.mms_config import CONFIG
> import my_setup
> print(CONFIG)
> ```

Yes, it should be.
