### ISSUE TITLE
Can I download latest version of PSP data?

### ISSUE THREAD

**Issue by nsioulas** [spedas/pyspedas#175]
I am trying to download PSP data, for example SPC data from the first encounter.

On the SWEAP website: http://sweap.cfa.harvard.edu/data/sci/sweap/spc/L3/2018/11/

I can see that there is a version  26 of the CDF file. However, when using:

            spcdata = pyspedas.psp.spc(trange=[t0, t1], datatype='l3i', level='l3', 
                                    varnames = [
                                        'np_moment',
                                        'wp_moment',
                                        'vp_moment_RTN',
                                        'vp_moment_SC',
                                        'sc_pos_HCI',
                                        'sc_vel_HCI',
                                        'carr_latitude',
                                        'carr_longitude'
                                    ], 
                                    time_clip=True)

I am getting the first vesrion of the CDF file (V01). Is there a functionality that would allow me to download the latest version that I am not aware of?

Thanks!

**Comment by supervised** [comment]
The PSP load routine currently loads data from SPDF, so the latest versions might not be available. I think they're working on adding support for the Harvard server under the 'psp' branch, though - so you could try updating to the latest bleeding edge 
 with:

`pip install --upgrade https://github.com/spedas/pyspedas/psp.zip`

I suggest doing this in a new virtual environment (since this is the bleeding edge).

**Comment by nsioulas** [comment]
Thank you for your response!

I am getting this error though:

ERROR: HTTP error 404 while getting https://github.com/spedas/pyspedas/psp.zip
ERROR: Could not install requirement https://github.com/spedas/pyspedas/psp.zip because of HTTP error 404 Client Error: Not Found for url: https://github.com/spedas/pyspedas/psp.zip for URL https://github.com/spedas/pyspedas/psp.zip

**Comment by nsioulas** [comment]
Thank you!

I am getting this error though:

ERROR: HTTP error 404 while getting https://github.com/spedas/pyspedas/psp.zip
ERROR: Could not install requirement https://github.com/spedas/pyspedas/psp.zip because of HTTP error 404 Client Error: Not Found for url: https://github.com/spedas/pyspedas/psp.zip for URL https://github.com/spedas/pyspedas/psp.zip

**Comment by huangzesen** [comment]
This can be done with two methods:
1. use github desktop, switch branch to psp
2. use `git checkout psp` to switch to psp branch

**Comment by supervised** [comment]
> I am getting this error though:

Ah - sorry - I left off 'archive' from the link! the correct command is:

`pip install --upgrade https://github.com/spedas/pyspedas/archive/psp.zip`

**Comment by nsioulas** [comment]
@supervised  Thank you!

**Comment by jameswilburlewis** [comment]
@AyrisA, I see you're one of the most recent contributors to the psp branch....do you know if support for downloading from the Harvard server is planned any time soon?

**Comment by AyrisA** [comment]
Hi Jim et al. --
I thought the support for this was already implemented.  Not only in the psp branch, but also in main.

Let me take a look at what's going on and get back to you (it's been a while since I've been in here :) )

**Comment by AyrisA** [comment]
@nsioulas You should be able to pass your credentials through the `username=` and `password=` arguments to `pyspedas.psp.spc()`.  See: https://pyspedas.readthedocs.io/en/latest/psp.html

Please let us know if this doesn't work and we can look into debugging.
Thanks!
-Ayris
