### ISSUE TITLE
Is it possible to add regex support to the download function?

### ISSUE THREAD

**Issue by huangzesen** [spedas/pyspedas#177]
The unpublished psp database have several versions of cdf available in the mean time. it would be nice if the download function support regular expression. I can actually help on this, but I need some guidance.

**Comment by supervised** [comment]
Yeah, definitely possible! I should be able to make the changes this week.

**Comment by supervised** [comment]
I just added a keyword, `regex` that tells the download function to use regular expressions in the filename instead of unix-style pattern matching

**Comment by huangzesen** [comment]
Thks!!!!
