### ISSUE TITLE
Remote index not found for Greenland Magnetometers

### ISSUE THREAD

**Issue by dcsozturk** [spedas/pyspedas#197]
I am getting a Remote index not found error when I try to use pyspedas.themis.gmag command to download Greenland magnetometer data. This is because of an additional 'mag/' string in load.py, Line 167. 

The correct string for Greenland magnetometers should read: 

if in_greenland:
        pathformat.append('thg/greenland_gmag/' + level
                                          + site + '/%Y/thg_' + level
                                          + '_mag_' + site + '_%Y%m%d_v??.cdf')

Could this pathformat be updated?

**Comment by supervised** [comment]
Thanks for the report! I just committed a fix.
