### ISSUE TITLE
Please use logging instead of prints

### ISSUE THREAD

**Issue by sapols** [spedas/pyspedas#212]
There was some conversation in the PyHC Element chat this morning about suppressing all the printouts pySPEDAS generates when you load data (`Time clip was applied to...`, `Loading variables: ...`, etc).

The OP ended up using a hack like this to redirect stdout: https://gist.github.com/vikjam/755930297430091d8d8df70ac89ea9e2

But it was brought up that if pySPEDAS used logging (https://docs.python.org/3/library/logging.html) instead of standard `print()`, it would allow messages to be printed by default but users would have some control over what is shown if they wanted. A few people immediately agreed this would be a good change. 

Please consider this a vote for this feature request?

**Comment by supervised** [comment]
Great idea - I'll go ahead and fix this where I can!

**Comment by jameswilburlewis** [comment]
I believe we've now converted the bulk of the noisy pyspedas progress messages to logging calls.  The updates are available in pyspedas 1.4.28, just released to pypi.
