### ISSUE TITLE
pyspedas/pyspedas/mms/feeps/mms_feeps_remove_bad_data.py line 50

### ISSUE THREAD

**Issue by PluckZK** [spedas/pyspedas#225]
Are October 2017 and October 2018 the starting time for bad eyes tables? 
If so, then you should not take the closest table, but take the table according to the time period.

**Comment by supervised** [comment]
Thanks for the report! 

This is probably a better question for the MMS FEEPS team. I did confirm with Joe Fennell, just a few weeks ago, that the current way this works should be fine.

**Comment by PluckZK** [comment]
> Update: turns out, this is a different spot than the one I confirmed with Joe Fennell a few weeks ago (though very similar question/issue).
> 
> I checked the IDL code (the team's official routine) and it works the same way.
> 
> I suspect the current algorithm works the way the team intends for it to work, but you could always check with them to be sure.

Thank you vrey much !
