### ISSUE TITLE
The scope of the for loop in Feeps PAD

### ISSUE THREAD

**Issue by PluckZK** [spedas/pyspedas#245]
https://github.com/spedas/pyspedas/blob/e4a6feabf99e10db9636ae28039c9b573b86e8e4/pyspedas/mms/feeps/mms_feeps_pitch_angles.py#L144
https://github.com/spedas/pyspedas/blob/e4a6feabf99e10db9636ae28039c9b573b86e8e4/pyspedas/mms/feeps/mms_feeps_pitch_angles.py#L223
This for loop ranges from 144 lines to 223 lines,  variable **idx_ Maps** will be calculated once for each loop.

**Comment by supervised** [comment]
Thank you for the bug report (and for doing such a thorough review of the FEEPS code)! 

I compared the code with IDL, and the indentation of lines 183-223 should be shifted to the left (so it's not in that for loop). I just checked in a fix.

Thanks again!

**Comment by PluckZK** [comment]
> Thank you for the bug report (and for doing such a thorough review of the FEEPS code)!
> 
> I compared the code with IDL, and the indentation of lines 183-223 should be shifted to the left (so it's not in that for loop). I just checked in a fix.
> 
> Thanks again!

Thank you very much for your reply!  : )
