### ISSUE TITLE
ValueError when time averaging data

### ISSUE THREAD

**Issue by nwijsen** [spedas/pyspedas#308]
Hello,

The avg_data function throws a `ValueError: too many values to unpack` when the pytplot variable that I am trying to average has more than 1 dimension (e.g., when spec_bins are also present). The error seems to come from line 71 in  [pyspedas/analysis/avg_data.py](https://github.com/spedas/pyspedas/blob/master/pyspedas/analysis/avg_data.py): `time, data = pytplot.get_data(old)`. The reason being that the namedtuple returned by pytplot.get_data() contains more than 2 elements when the dimension of the variable exceeds one.

One quick fix that worked for me is using instead: `time, data, *kw = pytplot.get_data(old)`

**Comment by supervised** [comment]
Thanks for the report! 

@nickssl can you take a look at this?

**Comment by supervised** [comment]
Thanks again for the report! @nickssl checked in a fix for this - I'll roll out a new version with the fix today.

@jameswilburlewis - it looks like this routine needs some more improvements (e.g., support for spectrograms, higher dimensional data) that are probably worth opening a task for

**Comment by supervised** [comment]
This should be fixed now in v1.4.23

**Comment by jameswilburlewis** [comment]
Yes, it would be a good idea to support higher dimensional data in the routine and the test suite.  I've assigned to Nick.

**Comment by nickssl** [comment]
Done!

**Comment by nickssl** [comment]
Done!

**Comment by nickssl** [comment]
Completed.
