### ISSUE TITLE
twavpol uses incorrect averaging window

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#315]
Same issue existed in IDL -- it used a predefined 7-bin averaging window, so smaller bin counts would get skewed/scaled results, while larger bin counts would crash with out of bounds array access.

**Comment by ThiGli** [comment]
I ran across the bug a few months ago and fixed it with the following modification. I'm not sure, if this is what you're looking for, but I thought, I just share what worked for me.

I modified the matrix smoothing [here](https://github.com/spedas/pyspedas/blob/master/pyspedas/analysis/twavpol.py#L489) by replacing the part with this:
```
windmid = len(aa) // 2
windstart, windend = windmid - nosmbins // 2, windmid + nosmbins // 2 + 1
hann = aa[windstart:windend] / aa[windstart:windend].sum()
for k1 in range(3):
    for k2 in range(3):
        ematspec[KK, :, k1, k2] = np.convolve(matspec[KK, :, k1, k2], hann, mode = "same")

```
It still uses the "hanning" window `aa` from twavpol (though I do not know how exactly `aa` was cacluclated) selecting the middle from it,  and normalizes it before convolution with the spectral matrix. Using `np.convolve` speeds things up drastically, but still has the problem, that the normalization fails at the edges (lowest `nosmbins // 2` frequencies and highest `nosmbins // 2` frequencies).

**Comment by ThiGli** [comment]
Futhermore, the [squaring of the smoothed spectral matrix](https://github.com/spedas/pyspedas/blob/262abc8762454e45af0392fb93c74b25e95d3da0/pyspedas/analysis/twavpol.py#L519) could be simplified by just writing
```
matsqrd[KK] = ematspec[KK] @ ematspec[KK]
```
using the `@`-shorthand for `np.matmul`, which applies matrix multiplication over the last 2 axes automatically.
Using `wpol_matsqrd` function looked a bit obscure to me...

**Comment by jameswilburlewis** [comment]
@ThiGli Thanks for the suggestions!  I'm working on this in the themis branch, and have some local changes that haven't been pushed out yet.  I'm using np.hamming() to generate a properly sized and normalized smoothing window that matches the predefined array from the original IDL code (which was incorrectly described as a Hanning window).  I added some tests to compare the IDL and Python results, so it should be pretty straightforward to incorporate your suggestions and verify that they give the same results.

**Comment by jameswilburlewis** [comment]
This is fixed in the themis branch.  I've opened a separate issue for refactoring the matrix squaring operation.
