### ISSUE TITLE
tplot crashes on a variable created via tplot_restore

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#317]
tplot_restore seems to be creating some metadata attributes as bytes rather than strings.   

I've opened an issue for pytplot: [https://github.com/MAVENSDC/PyTplot/issues/167](https://github.com/MAVENSDC/PyTplot/issues/167)

**Comment by QTSth** [comment]
I just bumped into similar problem as well.
My error message corresponds to the file "TVarFigure1D.py", line 163 in def _setyaxislabel(self):
    ysublabel = pytplot.data_quants[self.tvar_name].attrs['plot_options']['yaxis_opt']['axis_subtitle'].replace(" \ ", " <br> ")

TypeError: a bytes-like object is required, not 'str'

The others seem correctly treated except for y sublabels just like James's case, and the same error pops up when I use different .tplot files.

**Comment by jameswilburlewis** [comment]
That fixed my issue, thanks!
