### ISSUE TITLE
Cannot associate minvar branch with an issue

### ISSUE THREAD

**Issue by xandrd** [spedas/pyspedas#322]
I woiuld like to associate issue #321 with the branch `minvar`. However, the branch cannot be found:
![image](https://user-images.githubusercontent.com/13282744/218214862-6b4b6026-ae66-4bbe-afc3-0bc9786579f9.png)

The only branches that are visible are the ones created by @supervised. 

Is there a project setting that makes other branches "invisible"?

**Comment by supervised** [comment]
I'm not sure why it's not finding the branch

**Comment by jameswilburlewis** [comment]
I was able to create a new branch "dummy_branch_test_github_issues" and link it to this issue via the sidebar, though the "minvar" branch doesn't appear in the list for me, either.  @xandrd , I wonder if it has something to do with our respective roles.   When I look at the pyspedas repository settings for "Collaborators and teams", your account shows up with "Mixed roles", and it says that as an organization owner, you cannot be assigned any other role than "Maintain".   Curiously, Eric and my accounts don't show up in that list of accounts at all.   I wonder if you create another branch, if that one would show up in the "Development" sidebar search?  Curious and confusing!  It seems this feature was only added late last year, so it could be a bug in Github Issues itself.

**Comment by jameswilburlewis** [comment]
By the way, "dummy_branch_test_github_issues" was created from the repository page, rather than being created directly from the sidebar.

**Comment by xandrd** [comment]
It looks like it is a relatively new feature, (e.g. "...you can now link existing branches..."):
https://github.blog/changelog/2022-09-07-link-existing-branches-to-an-issue/
Perhaps, there is a bug with a GutHub itself. Some other branches, like `geopack` or `docs-updates` are also unavailable. 
I assume since this is a new feature it will work only with **future** branches and pull requests.
