### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by ericthewizard** [spedas/pyspedas#327]
There are a lot of updates that need to be made to the documentation, so I'm creating an issue for tracking them.

1. From #326, we need to update the docstrings for the `notplot` keyword to include some additional text on the lack of post-processing when using this keyword
2. Example PNGs need to be updated for the readthedocs docs (some are missing entirely, e.g., SOHO, ELFIN, probably several more)

**Comment by jameswilburlewis** [comment]
Additional documentation standards that should apply to header comments/docstrings for all pyspedas and pytplot routines that are meant to be called by users:

1) All parameters documented and kept up to date with implementation
2) Brief one-line description (exposed via 'help' and 'libs' tools)
3) Return values documented and kept up to date with implementation
4) Some brief usage examples
5) Links to any relevant notebooks with more detailed examples.
6) Type hints wherever applicable in function definitions

Items 1,2, and 3 are already in fairly decent shape for many routines, but there are cases where they've gone out of sync with the implementation.  4, 5, and 6 need work across the board.

Please take a few moments any time you edit or read pyspedas code, and ensure that the comments are complete and up to date.   We will probably make specific assignments as priority dictates.

**Comment by jameswilburlewis** [comment]
Our docs are in much better shape now, we'll open new issues for specific improvements needed.
