### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by rgoalcast** [spedas/pyspedas#33]
AttributeError: module 'pyspedas' has no attribute 'get_spedas_prefs'

What is this error and how can it solve?

**Comment by supervised** [comment]
What version of pySPEDAS are you using? get_spedas_prefs was a file that was depreciated/deleted awhile ago

Assuming the error is coming from somewhere in pySPEDAS, you should be able to fix it by updating to the latest:

pip install pyspedas --upgrade

if you're using get_spedas_prefs in your code, we suggest using environment variables to find the data directories now (e.g., SPEDAS_DATA_DIR)

**Comment by rgoalcast** [comment]
Version is 1.0.3 after updates and I am trying command pydivide.download_files(insitu=True, list_files=True), found this error, how can I solve?

Traceback (most recent call last):

  File "<ipython-input-8-9493beb3da27>", line 1, in <module>
    pydivide.download_files(insitu=True, list_files=True)

  File "/Users/username/opt/MAVENSDC-Pydivide-626c30f/pydivide/download_files.py", line 142, in download_files
    mvn_root_data_dir = utils.get_root_data_dir()

  File "/Users/username/opt/MAVENSDC-Pydivide-626c30f/pydivide/download_files_utilities.py", line 134, in get_root_data_dir
    prefs = pyspedas.get_spedas_prefs()

AttributeError: module 'pyspedas' has no attribute 'get_spedas_prefs'

**Comment by supervised** [comment]
Ah, it looks like pydivide is still using get_spedas_prefs; I just submitted a PR to fix this in pydivide

**Comment by supervised** [comment]
Thanks for reporting this! The problem should be fixed in pydivide soon, but in the mean time, you can fix it locally by updating lines 132-136 of:

/Users/username/opt/MAVENSDC-Pydivide-626c30f/pydivide/download_files_utilities.py

To be:
     import os
     # Get preferred data download location for pyspedas project
     spedas_data_dir = os.getenv('SPEDAS_DATA_DIR')
     if spedas_data_dir:
         return spedas_data_dir

instead of:
    import pyspedas
    # Get preferred data download location for pyspedas project
    prefs = pyspedas.get_spedas_prefs()
    if 'data_dir' in prefs:
        return prefs['data_dir']

**Comment by rgoalcast** [comment]
Yes It's working, in read command, I am getting Index error? How can it solve?
insitu, iuvs = pydivide.read('2015-12-25')

File "/Users/username/opt/anaconda3/lib/python3.8/site-packages/pydivide/read.py", line 77, in read
    date = re.findall(r'_(\d{8})', file)[0]

IndexError: list index out of range

**Comment by supervised** [comment]
I'm not entirely sure (I'm not a user of pydivide) - though it looks like there may be a bug in pydivide when you specify a date to the read function instead of a file name. Which dataset are you trying to get access to? I ask because the dataset you're looking for might be available through the pyspedas.maven module.

**Comment by rgoalcast** [comment]
import pydivide
Traceback (most recent call last):

  File "/Users/username/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-11-d8cc91d4eb39>", line 1, in <module>
    import pydivide

  File "/Users/username/opt/MAVENSDC-Pydivide-626c30f/pydivide/__init__.py", line 2, in <module>
    from .altplot import altplot

  File "/Users/username/opt/MAVENSDC-Pydivide-626c30f/pydivide/altplot.py", line 6, in <module>
    from .utilities import get_inst_obs_labels, param_list, orbit_time, range_select

  File "/Users/username/opt/MAVENSDC-Pydivide-626c30f/pydivide/utilities.py", line 8, in <module>
    from . import download_files_utilities as utils

  File "/Users/username/opt/MAVENSDC-Pydivide-626c30f/pydivide/download_files_utilities.py", line 134
    spedas_data_dir = os.getenv('SPEDAS_DATA_DIR')
    ^
IndentationError: unexpected indent


I am importing pydivide, error is coming, Yes I am exploring pyspedas module, I am  trying with IUVS data. How can I correct error ? Thank you.

**Comment by supervised** [comment]
It looks like you have a problem with the indentation on line 134 of download_files_utilities.py; if the indentation appears correct, I suggest making sure you're not mixing spacing and tabbing for indentation
