### ISSUE TITLE
pytplot:  Need a data_gap attribute that applies per variable, not to a whole plot

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#340]
This is available as a plot option, but it applies to the entire plot rather than a single variable.

**Comment by jameswilburlewis** [comment]
See also: https://github.com/spedas/pyspedas/issues/358

**Comment by jimm02** [comment]
Data_gap option exists both as a global tplot_option and option for individual variables: Here is an example using ERG data:
import pyspedas
import pytplot
#load data and create compound variable
pyspedas.erg.mepi_nml( trange=['2017-04-02 00:00:00', '2017-04-03 00:00:00'] )
pytplot.store_data( 'erg_mepi_l2_omniflux_FPDO_combined', data='erg_mepi_l2_omniflux_FPDO erg_mepi_l2_omniflux_FPDO_tof' )

#set global data_gap
pytplot.tplot_options('data_gap', 33.0)
pytplot.tplot(['erg_mepi_l2_omniflux_FPDO','erg_mepi_l2_omniflux_FPDO_tof', 'erg_mepi_l2_omniflux_FPDO_combined'], display=False, save_png = 'ERG_data_gap_all' )

![ERG_data_gap_all](https://github.com/spedas/pyspedas/assets/124631823/74485fdc-04b1-4f70-9e9a-035f437e2bc3)

#reset data_gap to test for individual variables, can use None too
pytplot.tplot_options('data_gap', 0)

#set data_gap for one variable:
pytplot.options('erg_mepi_l2_omniflux_FPDO', option='data_gap', value=33.0)

pytplot.tplot(['erg_mepi_l2_omniflux_FPDO','erg_mepi_l2_omniflux_FPDO_tof', 'erg_mepi_l2_omniflux_FPDO_combined'], display=False, save_png = 'ERG_data_gap_1' )

![ERG_data_gap_1](https://github.com/spedas/pyspedas/assets/124631823/aedbe5f4-8721-463e-a019-f8aaeae1e11b)

#Turn off gap
pytplot.options('erg_mepi_l2_omniflux_FPDO', option='data_gap', value=0)
