### ISSUE TITLE
Can't load wind 3dp_pm data

### ISSUE THREAD

**Issue by qiyycc** [spedas/pyspedas#346]
I run:
`beg_str = '2018-11-6'`

`end_str = '2018-11-7'`

`threedp_vars = pyspedas.wind.threedp(trange=[beg_str, end_str], datatype='3dp_pm',
                                time_clip=True)`
and get threedp_var = []

how could I fix this?

Thanks!

**Comment by jameswilburlewis** [comment]
This is fixed in the themis branch.   The updates should be merged into the master branch fairly soon, then we'll do a version bump and update pyspedas on PyPI.

**Comment by qiyycc** [comment]
Thanks a lot!

**Comment by jameswilburlewis** [comment]
pyspedas version 1.4.28, just released to pypi, now supports this WIND data type and several others.
