### ISSUE TITLE
Basic PyTplot examples need to be added to the Exploring the Heliosphere notebook

### ISSUE THREAD

**Issue by ericthewizard** [spedas/pyspedas#352]
Davin suggested we add some examples of `get_data` and `store_data` to our Exploring the Heliosphere with Python notebook:

https://github.com/spedas/pyspedas_examples/blob/master/pyspedas_examples/notebooks/Exploring_the_Heliosphere_with_Python.ipynb

Considering the purpose of this notebook is to showcase the power of PySPEDAS and PyTplot alongside SunPy, there are probably a bunch of other examples we can add.

**Comment by jameswilburlewis** [comment]
I would like to keep that particular notebook at a higher, more analytic level -- we have several other repos for more beginner-oriented tutorial notebooks demonstrating the nuts and bolts of the lower level tools.
