### ISSUE TITLE
Multi-tplot variable does not work properly?

### ISSUE THREAD

**Issue by horit** [spedas/pyspedas#358]
When I create a multi-tplot variable by combining two spectrum-type tplot variables and plot it as a whole, I encounter the following error. As a reference, I just copied essentially the same code but in IDL/SPEDAS and its resultant plot as well as the code for PySPEDAS. How should I further proceed with this to generate the same plot as IDL/SPEDAS does? 

```
;; by IDL/SPEDAS
timespan, '2017-04-02'
erg_load_mepi_nml, datatype='omniflux'
store_data, 'erg_mepi_l2_omniflux_FPDO_combined', data='erg_mepi_l2_omniflux_FPDO'+['', '_tof']
ylim, 'erg_mepi_l2_omniflux_FPDO_combined', 6, 100, 1
tplot, 'erg_mepi_l2_omniflux_FPDO*'
```
<img width="908" alt="by IDL/SPEDAS" src="https://user-images.githubusercontent.com/3747180/225841463-5360595c-0551-4ab0-a060-b8bb102c5a28.png">

```
## by PySPEDAS
import pyspedas
import pytplot
pyspedas.erg.mepi_nml( trange=['2017-04-02 00:00:00', '2017-04-03 00:00:00'] )
pytplot.store_data( 'erg_mepi_l2_omniflux_FPDO_combined', data='erg_mepi_l2_omniflux_FPDO erg_mepi_l2_omniflux_FPDO_tof' )
pytplot.tplot(['erg_mepi_l2_omniflux_FPDO','erg_mepi_l2_omniflux_FPDO_tof', 'erg_mepi_l2_omniflux_FPDO_combined'] )


---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-54df4c186d90> in <module>
----> 1 pytplot.tplot(['erg_mepi_l2_omniflux_FPDO','erg_mepi_l2_omniflux_FPDO_tof', 'erg_mepi_l2_omniflux_FPDO_combined'] )

~/.pyenv/versions/3.9.6/envs/39_pydarn_pyspedas/lib/python3.9/site-packages/pytplot/tplot.py in tplot(name, var_label, slice, combine_axes, nb, save_file, gui, qt, bokeh, save_png, display, testing, extra_functions, extra_function_args, vert_spacing, pos_2d, pos_3d, exec_qt, window_name, interactive, xsize, ysize, save_eps, save_svg, save_pdf, save_jpeg, dpi, fig, axis, pseudo_plot_num, second_axis_size, return_plot_objects)
    158
    159     if qt == False and bokeh == False:
--> 160         return mpl_tplot(name, var_label=var_label,
    161                                xsize=xsize,
    162                                ysize=ysize,

~/.pyenv/versions/3.9.6/envs/39_pydarn_pyspedas/lib/python3.9/site-packages/pytplot/MPLPlotter/tplot.py in tplot(variables, var_label, xsize, ysize, save_png, save_eps, save_svg, save_pdf, save_jpeg, dpi, display, fig, axis, pseudo_plot_num, pseudo_right_axis, pseudo_yaxis_options, pseudo_zaxis_options, pseudo_line_options, pseudo_extra_options, second_axis_size, slice, return_plot_objects)
    468                 ztitle_color = None
    469
--> 470             if zaxis_options.get('axis_color') is not None:
    471                 ztitle_color = zaxis_options['axis_color']
    472

AttributeError: 'NoneType' object has no attribute 'get'

```

**Comment by horit** [comment]
Thanks, Eric! It works now, giving no critical error. However, the resultant spectrum plot for the multi-tplot variable looks different from that of IDL/SPEDAS, which is correct. Data for the 1st and 2nd panels are obtained exclusively in time by a spacecraft, they should appear exclusively also on a plot. It looks that both spectra partly overlap with each other, resulting in a bit different plot for the multi-tplot variable. Will this be fixed if the "data_gap" attribute is implemented for individual tplot variables? I think that someone else has posted a separate issue on it here some while ago.  

<img width="919" alt="by PySPEDAS with pytplot-mpl-temp v2.1.21" src="https://user-images.githubusercontent.com/3747180/225849870-272d9759-9486-4708-a0f2-1379fbc307fa.png">

**Comment by jameswilburlewis** [comment]
In the IDL code for erg_load_mepi_nml, there are calls that set the datagap option, like this:

  options, vns, spec=1, ysubtitle='[keV/q]', ztickunits='scientific', extend_y_edges=1, $
           datagap=33., zticklen=-0.4

So I think this needs to be fixed or implemented in pytplot.

**Comment by jimm02** [comment]
Note the data_gap option is now available as both a global option and an option for individual variables.
