### ISSUE TITLE
An installation error 

### ISSUE THREAD

**Issue by scarletteshu** [spedas/pyspedas#36]
the error is:
`ERROR: cdasws 1.7.21 has requirement requests>=2.20, but you'll have requests 2.9.1 which is incompatible.`

I can't find any solve for this problem online, sorry to bother you, can you tell me how to solve it?

**Comment by supervised** [comment]
Try:

pip install requests --upgrade

This should upgrade your version of the requests library to 2.24.0, which should be compatible with cdasws 1.7.21
