### ISSUE TITLE
Time tagging issue for RBSP

### ISSUE THREAD

**Issue by Rhyst223** [spedas/pyspedas#37]
Hi,

I am using RBSP data (EMFISIS/EFW) for a current study and upon comparison with the raw data from the source, data pulled in with pyspedas appears to be time shifted forwards by an hour. Just wanted to bring this to your attention in case you may not have known!

**Comment by supervised** [comment]
Interesting - thanks for the report! 

Which data products are you comparing and to which source? 

As a quick test, I loaded EMFISIS data using IDL SPEDAS with:

```
timespan, '2019-07-07', 1, /day
rbsp_load_emfisis, probe='a', cadence='hires', coord='sm'
```

This loads the L3 data from emfisis.physics.uiowa.edu. 

And I loaded EMFISIS data using pySPEDAS with:

`pyspedas.rbsp.emfisis(trange=['2019-07-07', '2019-07-08'], level='l3', cadence='hires', coord='sm')`

This loads the L3 data from NASA SPDF. 

Comparing the two:

pySPEDAS:
```
>>> from pytplot import get_data
>>> t,b = get_data('Mag')
>>> t.shape
(5529600,)
>>> b.shape
(5529600, 3)
>>> b[0, :]
array([ -333.1 , -4956.33, 15164.5 ], dtype=float32)
>>> from pyspedas import time_string
>>> time_string(t[0])
'2019-07-06 23:59:57.923988'
```

and IDL:

```
rbsp_emfisis> get_data, 'rbspa_emfisis_l3_hires_sm_Mag', data=d
rbsp_emfisis> help, d
** Structure <1d749ae8>, 2 tags, length=110592000, data length=110592000, refs=1:
   X               DOUBLE    Array[5529600]
   Y               FLOAT     Array[5529600, 3]
rbsp_emfisis> d.Y[0, *]
      -333.10001
      -4956.3301
       15164.500
rbsp_emfisis> time_string(d.X[0], tformat='YYYY-MM-DD/hh:mm:ss.fff')
2019-07-06/23:59:57.923
```

They appear to be the same; but this is really just this one data product.

**Comment by Rhyst223** [comment]
Turns out that I was converting the time-stamps incorrectly using Python's datetime, as I was unaware of the time_string function.

Using `datetime.datetime.fromtimestamp(t)` time shifts everything forwards by an hour, and now I feel foolish!

**Comment by supervised** [comment]
Oh yes, fromtimestamp uses local time instead of UTC; I've made the same mistake a few times!
