### ISSUE TITLE
Move duplicated pytplot functionality to pytplot

### ISSUE THREAD

**Issue by ericthewizard** [spedas/pyspedas#372]
We have a lot of routines that implement the same functionality as routines in pytplot (e.g., avg_data). I think we should review all of these, move the core functionality to pytplot, and leave the current versions as wrappers around the pytplot versions (for backwards compatibility). We should also stop implementing features in pyspedas that already exist (or should exist) in pytplot.

**Comment by jameswilburlewis** [comment]
List of pyspedas routines that should move to pytplot (with pytplot equivalent, if it exists:)

- [ ] analysis/avg_data.py, possibly tplot_math/avg_res_data.py
- [ ] analysis/clean_spikes.py
- [ ] analysis/deriv_data.py, tplot_math/derive.py
- [ ] analysis/subtract_average.py
- [ ] analysis/subtract_median.py
- [ ] analysis/tcrossp.py
- [ ] analysis/tdeflag.py, tplot_math/deflag.py
- [ ] analysis/tdotp.py
- [ ] analysis/time_clip.py
- [ ] analysis/tinterpol.py, possibly tplot_math/interp_nan.py, tplot_math/tinterp.py
- [ ] analysis/tnormalize.py
- [ ] analysis/tsmooth.py
- [ ] analysis/yclip.py, tplot_math/clip.py
- [ ] utilities/data_exists.py
- [ ] utilities/tcopy.py, tplot_copy.py
- [ ] utillities/time_double.py
- [ ] utilities/time_string.py
- [ ] utilities/tkm2re.py
- [ ] utilitites/tnames.py

The ones that exist in both packages will need to be checked carefully to ensure they're doing the same thing before we point the pyspedas version at the pytplot version.

**Comment by jameswilburlewis** [comment]
First batch of routines have been moved to pytplot,, (pytplot-mpl-temp version 2.1.28 on pypi).  Many of them (in the themis branch) have been replaced with wrappers that forward to the pytplot versions, with 'info' level log messages advising updates to imports.

**Comment by jameswilburlewis** [comment]
Now that we're planning to eventually absorb pytplot into pyspedas, this issue is probably moot.
