### ISSUE TITLE
Development of the MTH5 interface

### ISSUE THREAD

**Issue by xandrd** [spedas/pyspedas#374]
From the proposal desription:

> This project is aimed to develop a software using Python 3, aimed to convert the magnetometer data from the IRIS and similar datasets utilizing MTH5 files into high-level data products and to provide access to the data via widely used space physics community software PySPEDAS.

**Comment by jameswilburlewis** [comment]
Yes, if it would make sense to split out the mth5_to_tplot functionality, that part should probably go into pytplot, with the dataset selection and download logic in pyspedas.

**Comment by xandrd** [comment]
I think for the ends user is would be easer to request magnetometer data from specific magnetometers. The users will not be downloading the MTH5 files, the MTH5 library will generate those files based on the user's input (e.g., selected number of stations, time period, etc.). So, it is not like a data reader but more like and interface via MTH5. Hence, it probably make sense to have is as a "mission" rather than a tool.
