### ISSUE TITLE
Update the MAVEN test suite

### ISSUE THREAD

**Issue by ericthewizard** [spedas/pyspedas#392]
The MAVEN test suite needs a lot of work. We're currently down to around ~41% test coverage for the MAVEN plug-in - which means large amounts of code in there aren't being tested; for example, the ~1,700 line file at:

/pyspedas/maven/utilities.py

only has ~16% coverage, according to Coveralls:

https://coveralls.io/builds/58379867/source?filename=pyspedas%2Fmaven%2Futilities.py

**Comment by jameswilburlewis** [comment]
The MAVEN directory now has over 90% test coverage.
