### ISSUE TITLE
Add test coverage to PyTplot

### ISSUE THREAD

**Issue by ericthewizard** [spedas/pyspedas#409]
Measuring code coverage with coveralls has been very useful for finding lines of code that aren't exercised by the test suite, e.g.,

https://coveralls.io/github/spedas/pyspedas

We should implement this in PyTplot as well; right now, we have no idea which lines of PyTplot are being executed by the test suite and which aren't, and there are probably numerous bugs that can be surfaced by implementing this.

**Comment by jameswilburlewis** [comment]
As a stopgap solution, we might try enabling coverage for the pytplot package in the pyspedas test actions.  I think it might be a simple edit to the .coveragerc file.  I'll give it a try next time I push to the themis branch.

**Comment by jameswilburlewis** [comment]
Adding pytplot to .coveragerc worked!

https://coveralls.io/jobs/118452015

Highlights:
About 30% coverage on pytplot overall, but some of that will be unused QTplotter code
81% coverage on the importers directory
46% coverage on tplot_math

**Comment by supervised** [comment]
Adding the current pytplot tests to our test suite (e.g., tests/test_matplotlib.py) should increase the coverage. 

This update also uncovered some untested files inside pyspedas (e.g., it looks like the geopack tests never made it to the workflow file).

**Comment by jameswilburlewis** [comment]
This issue is now moot since we plan to absorb pytplot into pyspedas.   We'll be sure to migrate the existing pytplot tests.
