### ISSUE TITLE
Check compatibility with pandas 2.0

### ISSUE THREAD

**Issue by supervised** [spedas/pyspedas#419]
pandas 2.0 was released today; we need to do some testing to make sure nothing is broken:

https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html

**Comment by jameswilburlewis** [comment]
I added a pandas==2.0.0 dependency to the themis branch, and it passed all unit tests (with akebono tests disabled).   I don't think the akebono test failure is related to pandas; the failure seemed to occur while trying to download data, and there were issues with this test that predate the 2.0.0 release.  On my Windows machine at home, with pandas 2.0.0 installed, the akebono tests run fine and all pass.

I will revert the pandas 2.0.0 dependency, and re-enable the akebono test just to make sure it fails there too.

**Comment by supervised** [comment]
Thanks for the update! From the errors (connection timeouts), we might actually be triggering some DDoS protection by hitting their servers too frequently
