### ISSUE TITLE
Add option to specify the slice plane's x-axis and normal to 2D slices routines

### ISSUE THREAD

**Issue by supervised** [spedas/pyspedas#424]
In our 2D slices routines in IDL, we have functionality to allow the user to specify the slice plane's x-axis and normal within the coordinates specified by the rotation and custom_rotation keywords; we should move this over

**Comment by PluckZK** [comment]
Great fix, thanks a lot!

**Comment by supervised** [comment]
These keywords are now available in mms_part_slice2d in pyspedas v1.4.27!
