### ISSUE TITLE
tplot_restore does not restore data_att structure

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#439]
See https://github.com/MAVENSDC/PyTplot/issues/174

Opening an issue here to track it in the SPEDAS project interface.

**Comment by supervised** [comment]
Update: still looking into this, but it appears that this isn't simple (due to the output of scipy's readsav function, and the wide variety of potential metadata). At a minimum, we'll need plenty of regression tests for tplot_restore to ensure I'm not breaking anything with my changes.

**Comment by supervised** [comment]
This one should be fixed in the bleeding edge now; I also added a test suite for tplot_restore

**Comment by jameswilburlewis** [comment]
It seems to be working, thank you!
