### ISSUE TITLE
PyTplot warnings are too verbose for MMS in some cases (e.g., FGM rdeltahalf variables) 

### ISSUE THREAD

**Issue by ericthewizard** [spedas/pyspedas#441]
We get errors when loading some MMS data - not really errors, more like warnings about some data products - these can be confusing if you're not used to ignoring them. We need to investigate ways to turn these off, or make it more clear that they're simply warnings to catch potential issues with the loaded data products (also switching to logging instead of prints).

**Comment by jameswilburlewis** [comment]
I've been wondering about the same thing.  One option would be a 'quiet' keyword to some of the pytplot routines, to suppress some or all of the log messages, for those calls that are expected to result in unwanted output.  "Lengths of x and y do not match" in store_data is another one that comes up a lot.

**Comment by supervised** [comment]
> I've been wondering about the same thing. One option would be a 'quiet' keyword to some of the pytplot routines, to suppress some or all of the log messages, for those calls that are expected to result in unwanted output. "Lengths of x and y do not match" in store_data is another one that comes up a lot.

Going this route might hide future, unexpected data problems (the ones that these warning messages are meant to catch). It might be better to allow pytplot to ignore specific variables when loading the data using wild cards (so like the opposite of varformat). For example, we could add an ignore_vars keyword, and for MMS FGM, we could ignore \*rdeltahalf\*, unless the user explicitly turns this off via some keyword to the FGM load routine.

**Comment by jameswilburlewis** [comment]
See https://github.com/MAVENSDC/PyTplot/issues/187

**Comment by jameswilburlewis** [comment]
Added exclude_format keyword argument to cdf_to_tplot, specifying a wildcard pattern for CDF variables to be skipped.  Added support to MMS and THEMIS load routines, MMS fgm loader now defaults to exclude_format='*rdeltahalf*'.
