### ISSUE TITLE
Github tests failing due to matplotlib version conflict between pytplot and basemap

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#453]
`pytplot currently requires matplotlib >= 3.7.   Earlier versions do not support legend_handles, but the older,  now deprecated, legendHandles.

In the pyspedas Github environment, the basemap package is getting pulled in via pythonpackage.yml.  basemap requires matplotlib < 3.7, so there is a version conflict.  So the automated test environment gets matplotlib 3.6.3, and ends up failing in test_cal_fit_tplot_metadata, because a pytplot call references legend_handles, which isn't available in that matplotlib version.

According to the basemap documentation (https://matplotlib.org/basemap/users/intro.html#deprecation-notice), basemap is deprecated, and new development should use the Cartopy package (https://scitools.org.uk/cartopy/docs/latest/) instead, although it may not yet include all the features from basemap.

The long term solution seems to be to switch to Cartopy and work around any not-yet-implemented features from basemap.

Short term, just to get the automated tests passing.....what would fail if we removed basemap from pythonpackage.yml?  Or maybe removing the offending pytplot call from test_cal_fit_tplot_metadata, or commenting that test out for the time being,  would be enough?

**Comment by supervised** [comment]
Oops! my fault - I just checked in a fix:

```
        try:
            handles = legend.legend_handles
        except AttributeError:
            handles = legend.legendHandles
        for legobj in handles:
```

We should be as liberal with the supported matplotlib versions as we can

**Comment by supervised** [comment]
> what would fail if we removed basemap from pythonpackage.yml? 

basemap is used by the SECS/EICS plug-in
