### ISSUE TITLE
Issues with netcdf_to_tplot

### ISSUE THREAD

**Issue by supervised** [spedas/pyspedas#469]
I was trying to load some GOES high resolution mag data from SPDF (stored in netCDF files), and I ran into 2 issues:

1. if you don't set a time variable name (just press enter on the first prompt), it seems to go into an infinite loop
2. if you do specify a time variable, with these files, I get the error:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/eric/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pytplot/importers/netcdf_to_tplot.py", line 133, in netcdf_to_tplot
>     unix_times = change_time_to_unix_time(time_var)
>   File "/Users/eric/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pytplot/importers/netcdf_to_tplot.py", line 14, in change_time_to_unix_time
>     units = time_var.units
> AttributeError: 'str' object has no attribute 'units'

**Comment by nickssl** [comment]
Fixed these issues in pytplot.netcdf_to_tplot.
The handling of the name of the time variable has changed. Now, the function attempts to determine the name of the time variable from the information inside the netcdf file itself, it does not ask the user to provide a name.
