### ISSUE TITLE
Issue with RBSP EMFISIS HFR spectra

### ISSUE THREAD

**Issue by ericthewizard** [spedas/pyspedas#472]
Just received a bug report regarding these data:

`pyspedas.rbsp.emfisis(trange=['2013-01-17', '2013-01-18'], datatype='hfr', level='l2', wavetype='spectra')`

The output I get is:

> 06-May-23 21:02:01: Downloading remote index: https://spdf.gsfc.nasa.gov/pub/data/rbsp/rbspa/l2/emfisis/hfr/spectra/2013/
> 06-May-23 21:02:02: Downloading https://spdf.gsfc.nasa.gov/pub/data/rbsp/rbspa/l2/emfisis/hfr/spectra/2013/rbsp-a_hfr-spectra_emfisis-l2_20130117_v1.2.4.cdf to rbsp_data/rbspa/l2/emfisis/hfr/spectra/2013/rbsp-a_hfr-spectra_emfisis-l2_20130117_v1.2.4.cdf
> 06-May-23 21:02:02: Download complete: rbsp_data/rbspa/l2/emfisis/hfr/spectra/2013/rbsp-a_hfr-spectra_emfisis-l2_20130117_v1.2.4.cdf
> 06-May-23 21:02:03: Length of v (1) and x (13224) do not match.  Cannot create tplot variable HFR_Spectra.
> 06-May-23 21:02:03: HFR_Spectra is currently not in pytplot.
> 06-May-23 21:02:03: HFR_Spectra is currently not in pytplot.
> 06-May-23 21:02:03: HFR_Spectra is currently not in pytplot.
> 06-May-23 21:02:03: HFR_Spectra is currently not in pytplot.
> 06-May-23 21:02:03: HFR_Spectra is currently not in pytplot.
> 06-May-23 21:02:03: HFR_Spectra is currently not in pytplot.
> ['HFR_Spectra']

**Comment by jameswilburlewis** [comment]
Data array for HFR_Spectra is timesx82.  Its DEPEND_1 is 1x82, and that extra leading dimension is the problem. Perhaps it's safe to reform 1xN arrays to N-element 1D arrays in cdf_to_tplot in this scenario. We do this with string-valued DEPEND_N variables, which seem to pick up extra length-1 leading and/or trailing dimensions.

**Comment by jameswilburlewis** [comment]
Fixed in the latest pytplot-mpl-temp.
