### ISSUE TITLE
Add magnetopause routines

### ISSUE THREAD

**Issue by ericthewizard** [spedas/pyspedas#482]
In IDL, we have routines for calculating the magnetopause location (e.g., `mpause_2` and `mpause_t96`); we still need to add these, as well as notebooks showing how to use them

**Comment by nickssl** [comment]
Added mpause_2.py and mpause_t96.py, which mirror the similar IDL functions. 

In the pyspedas_examples repository, added ex_mpause_2.py and ex_mpause_t96.py which are similar to the IDL examples in  crib_magnetopause.pro and give the same results. Also added the file PySPEDAS_magnetopause.ipynb which contains these examples in interactive jupyter notebook form.
