### ISSUE TITLE
TIme-zone dependent behaviour when passing in `datetime.datetime` objects as `trange` inputs.

### ISSUE THREAD

**Issue by STBadman** [spedas/pyspedas#487]
`pyspedas.utilities.dailynames` accepts `datetime.datetime` objects as input when it generates the list of files to download. However the behaviour of this can be timezone dependent. I just reran some code (`pyspedas.stereo.waves`) after moving timezone which caused the data file loaded to be one day later. The issue is how the datetime is cast to a string via `pytplot.daily_names`

You can reproduce the issue with these lines :

```python
import pyspedas
import datetime
datetime_in = datetime.datetime(2012,6,7,19,25)
timestring_out = pyspedas.utilities.time_string.time_string(datetime_in.timestamp())
print(datetime_in,timestring_out)
```

When i run this in the PST timezone during daylight savings the print statement yields:

2012-06-07 19:25:00 
 2012-06-08 02:25:00.000000

i.e. the output has been shifted forwards 7 hours ( the time difference between PST and UTC). Therefore a given pyspedas call with the above datetime would be expected to load a june 7th file but in fact loads june 8th.

I think this means the behaviour of `pyspedas.utilities.time_string.time_string` is that given a UNIX timestamp (which is not timezone dependent), it returns a time_string in the timezone of the local user. *I think this should instead default to returning a time_string at UTC* independent of user timezones since the dates of CDF filenames are all in UTC.

I couldn't quite figure out where the  `pyspedas.utilities.time_string.time_string` operation actually exists - it looks like it points to `pytplot` but couldn't find it there.

**Comment by supervised** [comment]
Thanks for the bug report! This should be fixed now. 

> I couldn't quite figure out where the pyspedas.utilities.time_string.time_string operation actually exists - it looks like it points to pytplot but couldn't find it there.

You might have been looking at the master branch of pytplot; all of the recent development has been occurring on the matplotlib-backend branch:

https://github.com/MAVENSDC/PyTplot/blob/matplotlib-backend/pytplot/time_string.py
