### ISSUE TITLE
PSP routine, last version of cdf files.

### ISSUE THREAD

**Issue by benjamin-short** [spedas/pyspedas#495]
Hi, 

When working with the latest version of the PSP routines I notice that it now loads all versions of the cdfs corresponding to a particular date. For example using: pys.psp.fields(trange=['2018-11-10','2018-11-11'],datatype='mag_RTN_4_Sa_per_Cyc',username=user,password=passw) loads data from both the v01 cdf and the v02 cdf at the same time. I'd like to just load the v02 cdf.

In previous pyspedas versions, this was handled by setting the keyword "last_version=True" in the fields routine but that keyword seems to have been removed in the latest version. Is there now a different way to specify that I'm only interested in the latest cdf version?

I also would be interested in collaborating on this module and have some minor additions to existing code that I could add.

**Comment by jameswilburlewis** [comment]
I've added the last_version parameter to the PSP load routines, and after a quick test I think it's working as expected.  We have a few other changes in progress, so we'll probably wait a few days to release a new version to pypi, but if you can pull the latest version of the master branch, please give it a try and let us know if it works for you.
!
Also, please do send us a pull request if you have other changes you'd like to include!
