### ISSUE TITLE
mms_part_getpad

### ISSUE THREAD

**Issue by Zhugexiaoyuanyuan** [spedas/pyspedas#499]
##I don't seem to see the mms_part_getpad function in pyspedas, so how can I use FPI-DIS data to plot Pitch-angle (PA) of ion differential energy fluxes.

**Comment by supervised** [comment]
You should be able to do this with mms_part_getspec; see the notebook at:

https://github.com/spedas/mms-examples/blob/master/advanced/Generate%20spectrograms%20and%20moments%20with%20mms_part_getspec.ipynb

for examples.
