### ISSUE TITLE
pyspedas corrupts downloaded CDFs from MMS SDC

### ISSUE THREAD

**Issue by phansel** [spedas/pyspedas#5]
Approximately 35% of CDFs downloaded through pyspedas.mms_load_x are missing their last 2-5 kilobytes. 

As downloaded by pyspedas, the file "mms1_dsp_fast_l2_swd_20150831_v0.4.0.cdf" is missing everything including and after byte 0x00070000. Similarly, "mms1_dsp_fast_l2_swd_20150825_v0.4.0.cdf" is truncated at byte 0x00074000.

To reproduce in python3:
```
import pyspedas
pyspedas.mms_load_dsp(trange=['2015-08-01','2015-09-01'],datatype='swd',level='l2',data_rate='fast')
```

If a corrupted file was downloaded, cdflib will throw error indicating that the tail of the file is missing: https://github.com/MAVENSDC/cdflib/issues/60

System:
> Linux abcdefg 5.1.15-arch1-1-ARCH #1 SMP PREEMPT Tue Jun 25 04:49:39 UTC 2019 x86_64 GNU/Linux

Installed Python 3.7.3 packages:
> astropy              3.2.1           
> cdflib               0.3.12          
> h5py                 2.9.0           
> numpy                1.16.4          
> pyspedas             0.8.6           
> pytplot              1.4.1           
> scipy                1.3.0           
> setuptools           41.0.1          
> six                  1.12.0          
> spacepy              0.2.0           
> urllib3              1.25.3

**Comment by supervised** [comment]
Thanks for the report! This should be fixed now.
