### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by Zhugexiaoyuanyuan** [spedas/pyspedas#502]
Hello, I want to get the cold plasma velocity (<257ev) using data from the Fast Plasma Investigation Dual Ion Spectrometer (FPI-DIS) instrument of the MMS satellite, how can this be handled? I have checked the pyspedas library for a long time and only see that obtaining the overall velocity of the ion

**Comment by supervised** [comment]
You should be able to do this with mms_part_getspec, e.g., 

```
from pyspedas.mms.particles.mms_part_getspec import mms_part_getspec
mms_part_getspec(output='moments', energy=[0, 257], species='i', trange=[...])
```

I suggest generating the velocity for the full energy range and comparing to the velocity found in the DIS CDFs (loaded with pyspedas.mms.fpi) before restricting the energy range.  Our moments algorithm is different from the team's, so you should verify that you can reproduce the official numbers for your time range prior to restricting the ranges. 

Hope this helps!
