### ISSUE TITLE
Update pyspedas and pytplot code for compatibility with cdflib version 1.0.1 and later

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#504]
cdflib 1.0 has just been released, with a number of breaking changes to the API.   For now, we have patched pyspedas requirements.txt to exclude cdflib 1.0 and later (with pytplot to follow), but both pyspedas and pytplot-mpl-temp will need changes to work with the new API.

I see that the psp and erg modules are directly calling cdflib routines.  If these calls can be replaced with cdf_to_tplot calls, we should work with the developers to rework those routines (and if not, consider making any missing functionality available via pytplot routines, to keep the cdflib dependencies as contained as possible).

**Comment by ericthewizard** [comment]
The requirements in requirements.txt should always be mirrored into setup.py (that's what PyPI uses)

**Comment by jameswilburlewis** [comment]
Implemented now in pytplot-mpl-temp version 2.2.11 plus erg and psp plugins, testing underway...

**Comment by jameswilburlewis** [comment]
I think everything works now with cdflib versions pre- and post- 1.0.0.  New pyspedas and pytplot-mpl-temp releases have been pushed to pypi, and the version pinning for cdflib has been removed in the package requirements.
