### ISSUE TITLE
Improve flexibility of time string formats in timebar

### ISSUE THREAD

**Issue by ericthewizard** [spedas/pyspedas#519]
If the user provides a time string to pytplot.timebar, the format is required to match the format: "%Y-%m-%d %H:%M:%S", otherwise they get an error, e.g., 

> ValueError: time data '2015-10-16/06:38' does not match format '%Y-%m-%d %H:%M:%S'

We need to update this to use the same fuzzy time parsing we use elsewhere in pytplot

**Comment by jameswilburlewis** [comment]
Replacing str_to_int with str_to_float_fuzzy seems to have done the trick.  Fixed in pytplot-mpl-temp version 2.1.42.
