### ISSUE TITLE
MAVEN SWEA routine doesn't load VAR or VARIANCE element

### ISSUE THREAD

**Issue by juditbergfalk** [spedas/pyspedas#524]
I'm trying to use Python to load SWEA data of the type 'arc3d'. I was told that IDL loads the variable called VAR (for variance) but I'm only able to load these variables: 'epoch', 'time_met', 'time_unix', 'binning', 'counts', 'diff_en_fluxes', 'geom_factor', 'g_engy', 'de_over_e', 'accum_time', 'energy', 'elev', 'g_elev', 'dindex', 'azim', 'g_azim', 'az_label', 'el_label', 'en_label', 'num_dists' .
Is there a way to add VAR to the downloadable data?
Thank you!

**Comment by jameswilburlewis** [comment]
That matches what I'm seeing with the command `pyspedas.maven.swea(spdf=True,datatype='arc3d',get_support_data=True)`.  I looked at the CDF with SPDF's cdfedit tool, and there is no variable VAR.  The file I'm looking at is:
 https://spdf.gsfc.nasa.gov/pub/data/maven/swea/l2/arc3d/2016/01/mvn_swe_l2_arc3d_20160101_v04_r01.cdf

I couldn't find an IDL routine in SPEDAS to load arc3d data.   So maybe there is unpublished code out there that's loading arc3d files from a different source?  If you could find out where these files are coming from, we could probably implement load routines in IDL and Python.

**Comment by juditbergfalk** [comment]
Sorry to respond so late. I was trying to figure some stuff out. You are right, there is no VAR in the CDF files or at least not the VAR I need. They calculate it fresh from the counts. VAR is the variance with digitization noise. There was a misunderstanding on my end. Sorry about that!
