### ISSUE TITLE
Add an option to re-download and overwrite the partially downloaded cdf file

### ISSUE THREAD

**Issue by PluckZK** [spedas/pyspedas#528]
When the user's network fluctuates or is disconnected, a common situation is that an incomplete cdf file is downloaded.
At this time, if the header file of the cdf file is complete, the variables of the incomplete cdf file can still be read, but this will cause errors in the subsequent processing. 
Is it possible to open a re-download option to the user, check the integrity of the cdf file, and if it is incomplete, re-download and overwrite the previously incomplete cdf file?
Thanks very much

**Comment by jameswilburlewis** [comment]
We do this in IDL by attempting to open each CDF as it's downloaded.  If the open fails, we do one more retry, and remove the partial file if the second attempt also fails.

If opening a partially downloaded CDF doesn't give an immediate error in Python, we might have to come up with a different strategy.   We'll look into it!

**Comment by nickssl** [comment]
Added code to download.py that tries to open a CDF or netCDF file, and if it cannot be opened, it downloads the file again for a second time. If after the second time, the file again cannot be opened, the code removes the file and informs the user to try downloading the file at a later time.

**Comment by PluckZK** [comment]
Is it possible to compare the downloaded file size with the server stored file size to determine whether the download is complete. as i know, if the header file of the cdf file is complete, the variables of the incomplete cdf file can still be read, but this will cause errors in the subsequent processing.
If you use the method of comparing file sizes, you can effectively solve this problem.
