### ISSUE TITLE
Compare the downloaded file size with the server stored file size

### ISSUE THREAD

**Issue by PluckZK** [spedas/pyspedas#544]
Added code to download.py that tries to open a CDF or netCDF file, and if it cannot be opened, it downloads the file again for a second time. If after the second time, the file again cannot be opened, the code removes the file and informs the user to try downloading the file at a later time.

_Originally posted by @nickssl in https://github.com/spedas/pyspedas/issues/528#issuecomment-1624757599_

**Comment by PluckZK** [comment]
Is it possible to compare the downloaded file size with the server stored file size to determine whether the download is complete.
As I know, if the header file of the cdf file is complete, the variables of the incomplete cdf file can still be read, but this will cause errors in the subsequent processing.
If you use the method of comparing file sizes, you can effectively solve this problem.

**Comment by PluckZK** [comment]
Many thanks to Nickssl for the solution, maybe double checking is more efficient?

**Comment by nickssl** [comment]
It is possible to compare the size of the server file to the size of the client file, but it is not very reliable. The client file may have the right size but it might be corrupted. And some web servers do not report the file size correctly (or at all). The most reliable and fast method for a file comparison between server and client is a hash (for example an MD5 hash), but most servers do not provide an MD5 hash for cdf files.
