### ISSUE TITLE
Delete temporary files after downloading data

### ISSUE THREAD

**Issue by KBergst** [spedas/pyspedas#555]
I am downloading large amounts of MMS data. I kept getting OOM errors despite having lots of space left on the system. After much debugging I determined that temporary files which are created during the file download process had completely filled up my `/tmp` folder. Manually deleting these files allowed the downloads to proceed.

I would like to request that each temporary file be deleted once the download of its respective data file has successfully completed. The files are created using `NamedTemporaryFile(delete=False)` so they will not be automatically deleted once the file is closed. I request that the temporary files are explicitly deleted wherever they are finished being used.

Thank you.

**Comment by ericthewizard** [comment]
Sorry for the trouble! I'm not entirely sure why I set `delete=False` there, but I just removed it (hopefully there wasn't some reason for it that I forgot).

**Comment by KBergst** [comment]
I can confirm the new version does not pile up files in `/tmp`. Thank you!

**Comment by ericthewizard** [comment]
So.. this fix ended up breaking downloads for Windows; I just checked in a better fix that should be available in v1.4.42.
