### ISSUE TITLE
No title while using option "name" or "title" for tplot variable 

### ISSUE THREAD

**Issue by xandrd** [spedas/pyspedas#564]
Steps to reproduce:
```python
pytplot.store_data("test", data={'x': [1, 2], 'y': [1, 2]})
pytplot.options("test", name="name", value="Test title")
pytplot.tplot("test")  # figure has no title

pytplot.options("test", option="title", value="Test title")
pytplot.tplot("test")  # figure has no title
```
![test](https://github.com/spedas/pyspedas/assets/13282744/d288413c-42b2-4733-905a-238bbbb24687)

Expected behavior:
Figure has a title while using option `name`

See also (table "Options"):
https://pytplot.readthedocs.io/en/latest/options.html

**Comment by ericthewizard** [comment]
Oh yeah, this hasn't been implemented for `options` (panel-level options), but it does work for `tplot_options` (figure-level options)

**Comment by ericthewizard** [comment]
I just added support for `title` and `name` set via `options`; you'll probably also have to set a custom `vertical_spacing` in `tplot_options` , if you're not setting it in the top panel
