### ISSUE TITLE
Comparison MMS FPI and FEEPS data

### ISSUE THREAD

**Issue by NikGrimm** [spedas/pyspedas#572]
Hi,
I would like to compare the omni directional EFlux density from FPI (*dis_energyspectr_omni_fast) with the FEEPS data. The load routine for FEEPS only return the omni directional intensity or count rate. If I'm not mistaken I would need the energy of the FEEPS particles to calculate the correct EFlux density. Theoretical this energy should be part of the dataset, shouldn't it? How can I access this energy or does another way exist to compare the two dataset in the same scale.

**Comment by ericthewizard** [comment]
Hello! 

You can access the energy channels using `get` (or `get_data`) in `pytplot`:

```python
from pytplot import get
d = get('mms1_epd_feeps_srvy_l2_electron_intensity_omni')
d.v
array([ 47.2,  65.9,  84.6, 103.4, 121.1, 139.2, 160.5, 185.3, 214.2,
       248. , 287.4, 333.4, 387.2, 450. , 523.2])
```

Note: some data products have time varying energy channels (e.g., burst mode FPI data), but FEEPS isn't time varying

**Comment by ericthewizard** [comment]
Also - I'm not sure if the EPD and FPI teams have fully investigated cross-calibration of these instruments, so please be sure to contact the FEEPS/FPI teams about this; they'll probably want to discuss potential issues with these comparisons...
