### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by XiangjingXu** [spedas/pyspedas#580]
ImportError: cannot import name 'time_datetime' from 'pytplot' occurs when running 'import pyspedas'

**Comment by XiangjingXu** [comment]
hear is the traceback:
Traceback (most recent call last):
  File "D:\program\PyCharm Community Edition 2023.2\plugins\python-ce\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "D:\program\PyCharm Community Edition 2023.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\program\enviroment\pycharm\lib\site-packages\pyspedas\__init__.py", line 4, in <module>
    from pytplot import time_string, time_datetime
ImportError: cannot import name 'time_datetime' from 'pytplot' (D:\program\enviroment\pycharm\lib\site-packages\pytplot\__init__.py)

**Comment by XiangjingXu** [comment]
we need to upgrate package pytplot-mpl-temp to the latest version.

**Comment by mshumko** [comment]
I ran into a similar bug as well in a clean Anaconda environment:

**Error**
```python
import pyspedas
  File "C:\Users\shumkms1\AppData\Local\anaconda3\envs\mms_conjunctions\Lib\site-packages\pyspedas\__init__.py", line 3, in <module>
    from pytplot import tnames
  File "C:\Users\shumkms1\AppData\Local\anaconda3\envs\mms_conjunctions\Lib\site-packages\pytplot\tnames.py", line 10, in <module>
    from pytplot import tplot_names
ImportError: cannot import name 'tplot_names' from 'pytplot' (unknown location)
```

**Environment**
Python 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:47:18) [MSC v.1916 64 bit (AMD64)] on win32
pyspedas==1.4.44 (newest at the time of writing this)
pytplot-mpl-temp==2.1.47

**Solution**
Downgrade pyspedas and pytplot-mpl-temp to my original version (not ideal).
```bash
python -m pip install pytplot-mpl-temp==2.1.34 pyspedas==1.4.28  
```

**Comment by jameswilburlewis** [comment]
@mshumko, is it possible that you have both pytplot and pytplot-mpl-temp installed?  If so, I would suggest uninstalling pytplot, then going back to pyspedas 1.4.44 and pytplot-mpl-temp 2.1.47 and see if the problem still occurs.   

I cannot reproduce the problem in my environment (Windows 10, Python 3.10, pyspedas 1.4.44, pytplot-mpl-temp 2.1.47)

**Comment by mshumko** [comment]
@jameswilburlewis, that worked, thanks for your suggestion! I kept getting spammed by `pytplot` to update it, so that was my mistake...

And `pytplot-mpl-temp` was automatically installed when I updated `pyspedas`, so my guess is that the two libraries are coupled such that their interfaces are incompatible if you update one without the other.

**Comment by jameswilburlewis** [comment]
I'm glad it worked out!  I am hoping to retire the older version of pytplot at some point, so we can rename pytplot-mpl-temp as the "one true pytplot" and avoid this ongoing confusion...
