### ISSUE TITLE
Set up OpenAI accounts for use in SPEDAS/PySPEDAS development

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#590]
Vassilis has given us the green light to set up paid accounts on openai.com for access to Chat-GPT4 to assist us with SPEDAS and PySPEDAS development.   Each of us should do the following:

- [ ] Sign up for an account on OpenAI.com (if you haven't already).
- [ ] Be prepared to temporarily change the login info so Misty, Emmanuel, or other purchaser can access the account and add the billing info.
- [ ] Let Jim L (UCB) or Emmanuel (UCLA) know when you're ready to proceed
- [ ] Be prepared to respond to any email or text confirmation requests as the accounts are updated
- [ ] After billing has been updated, change the password to secure the account.

**Comment by jmctiernan022** [comment]
Hi Jim,

My openai account username/email is ***@***.***, I reset my
pass to be: Temp$Pass323.

jm
