### ISSUE TITLE
Validate magnetic field models against IDL results

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#596]
Current tests in geopack directory only check for existence of tplot variables, not their contents

**Comment by nickssl** [comment]
geopack_recalc for IDL and python

Testing geopack_recalc on IDL and python, with default values for all keywords, gives similar results for tilt. The small difference is probably due to rounding errors. Notice that IDL computes tilt in degrees by default, python computes tilt in rad.

Time, IDL tilt, python tilt, difference
1104537600.0 -25.688066 -25.68803954113511 2.645886488750193e-05
1267401600.0 -10.112652 -10.112844328926181 -0.00019232892618070707
1451606400.0 -25.479425 -25.479427136575595 -2.136575595557133e-06
1598918400.0 5.3042021 5.304395379504903 0.0001932795049022218

**Comment by nickssl** [comment]
Comparing geopack_trace with default values, we get a 1-2% difference. 

IDL code and results

pro test_trace_simple
  t = 1451606400.0d
  g = [3.8498656, 4.7575000, 2.5203589]

  time=time_struct(t)
  geopack_recalc, time.year, time.doy, time.hour, time.min, time.sec, tilt=tilt

  geopack_trace, g[0], g[1], g[2], 1, 0, out_foot_x, out_foot_y, out_foot_z, rlim=60d, r0=1d, tilt=tilt 

  print, "time=", t
  print, "tilt=", tilt
  print, "out_foot=", out_foot_x, out_foot_y, out_foot_z
end
time=   1.4516064e+09
tilt=      -25.479425
out_foot=      0.63839987      0.27939591     -0.71720485

Python code and results

def test_trace_simple() -> None:
    t = 1451606400.0
    g = [3.8498656, 4.7575000, 2.5203589]

    tilt = geopack_recalc(t)
    tilt = tilt*180.0/np.pi

    out_foot_x, out_foot_y, out_foot_z, xx, yy, zz = geopack_trace(g[0], g[1], g[2], 1, inname='dipole', r0=1., rlim=60.)

    print("time=", t)
    print("tilt=", tilt)
    print('out_foot=', out_foot_x, out_foot_y, out_foot_z)

time= 1451606400.0
tilt= -25.479427136575595
out_foot= 0.6461359964741716 0.2752805458324856 -0.705663488711671

**Comment by nickssl** [comment]
Some comparisons between Fortran, IDL and python, can be found here: 

https://github.com/tsssss/geopack/blob/master/geopack/test_geopack1.md

**Comment by jameswilburlewis** [comment]
I'm looking at T89 model results from python and IDL.   There are significant differences (+/- 20000 nT) during THEMIS perigee passes.   I see the same differences when comparing the "igrf-only" results, without the T89 adjustments.  I'm not sure yet where this difference is coming from.  The tilt values from IDL and Python are very close, as you've noted.  IDL and Python are both using the most up to date IGRF model coefficients, according to the respective documentation.  So I'm not sure where the difference is coming from.   I haven't done the comparison with the geopack_2008 keyword yet;  I don't see this in the Python package, so it's not clear which version it's implementing.  (But would that even affect the IGRF field?). I also want to try calling the IGRF field calculations on their own, rather than having them passed through T89, in case that makes a difference.

IDL geopack

IDL test code:

```
; Load position data for field calculations
timespan,'2007-03-23'
thm_load_state,probe='a',coord='gsm',suffix='_gsm'

; Compute field model at s/c positions

; T89
tt89,'tha_state_pos_gsm',kp=2.0,/exact_tilt_times,newname='bt89',get_tilt='bt89_tilt'
tt89,'tha_state_pos_gsm',kp=2.0,/exact_tilt_times,/geopack_2008,newname='bt89_2008'
tt89,'tha_state_pos_gsm',kp=2.0,/exact_tilt_times,/igrf_only,newname='bt89_igrf'
tt89,'tha_state_pos_gsm',kp=2.0,/exact_tilt_times,/igrf_only,/geopack_2008,newname='bt89_igrf_2008'
```

Python test code:

```
        tt89('tha_state_pos_gsm', igrf_only=True)
        subtract('tha_state_pos_gsm_bt89','bt89_igrf',new_tvar='bt89_diff')
        tplot(['tha_state_pos_gsm_bt89','bt89_igrf','bt89_diff'])

```

**Comment by jameswilburlewis** [comment]
The pyspedas t89 wrapper was using the "dipole" internal model (geopack.dip()) rather than the IGRF model (geopack.igrf_gsm()).  I changed it to use IGRF, and now the results are acceptably close.

**Comment by jameswilburlewis** [comment]
There are some issues with the t96 and t01 models, which I've filed as separate issues:

t96: https://github.com/spedas/pyspedas/issues/616
t01: https://github.com/spedas/pyspedas/issues/617

The  IGRF, t89 and ts04 models seem to be giving results that are a good match to IDL.

I've added a test suite that downloads a file of IDL results to compare with Python: pyspedas/geopack/tests/geopack_idl_validation_tests.py
