### ISSUE TITLE
bokeh version conflict, Google Colab vs. pytplot

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#600]
Opening issue here for tracking purposes, see: https://github.com/MAVENSDC/PyTplot/issues/188

An update to the Google Colab environment introduced a version conflict between the bokeh version required by panel (from the Google Colab environment), and pytplot (which is pinned at bokeh < 3.0).   The bokeh dependency needs to be completely removed, or the HTMLPlotter code updated to be compatible with bokeh version 3.

**Comment by jameswilburlewis** [comment]
Right now I'm using a kludgey workaround, by installing a specific, older, version of the 'tables' package from the Colab environment that's causing the problem, but PyTplot definitely should be updated to resolve the issue going forward.

**Comment by jiashuwu89** [comment]
when i install pyspedas in colab, it unistalled bokeh 3.2.2 and installed 2.4.3 instead. The panel package doesn't work but i can use pyspedas and pytplot without any problems

**Comment by jiashuwu89** [comment]
and also i have to restart runtime and import pyspedas again after install it

**Comment by jameswilburlewis** [comment]
It's probably better at this point to implement https://github.com/spedas/pyspedas/issues/609 , rather than trying to patch the colab environment...

**Comment by jameswilburlewis** [comment]
pyspedas 1.4.47 with pytplot-mpl-temp version 2.1.52 removes the bokeh dependency and should resolve the version conflict in the Colab environment.
