### ISSUE TITLE
tplot difference between idl and python

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#609]
From Jiashu:

From Jiashu:

I’m comparing the tplot results from idl(left) with python(right). They are showing very different results around seconds=56.

The data for this spin are:
idl:            
data.v[5,*]
       150.98402144856061
       139.91197317746153
       128.83992490636246
       113.18346075014209
       95.748049842109126
       77.949549125689558
       60.919452729046370
       46.415908195102993
       38.009531261424790
       29.603154327746587

data.y[5,*]
                      NaN
       0.0000000000000000
       0.0000000000000000
       0.0000000000000000
       0.0000000000000000
       429.08953907276850
       0.0000000000000000
       0.0000000000000000
       0.0000000000000000
                      NaN

python:
data.v[5,:]
array([ 29.60487 ,  38.01094 ,  46.417015,  60.92013 ,  77.94982 ,
        95.74792 , 113.18286 , 128.83876 , 139.91019 , 150.98161 ],
      dtype=float32)

data.y[5,:]
array([        nan,   0.       ,   0.       ,   0.       , 429.0895209,
         0.       ,   0.       ,   0.       ,   0.       ,         nan])

The order of the pitch angel is flipped because i want all pitch angles in ascending order for plotting. 
This bin should center around pa = 77.94. But it is not the case for the python plot. 
Do you have any thoughts why?

<img width="1260" alt="PastedGraphic-2" src="https://github.com/spedas/pyspedas/assets/105754292/6dd48f3d-7090-4c9d-bcf6-e34509c11d38">

**Comment by jameswilburlewis** [comment]
From Jiashu:

Thanks for offering to check the code. Below shows an overlap of the plots. Black is from idl. yellow is from python. It seems that all spins are slightly shifted. Moreover, they appear to shift in opposite directions for ascending and descending spins. 
Could this discrepancy be related to how tplot function determines the boundary of each bin? i believe idl uses the midpoint of adjacent bins as boundaries. For instance, consider the leftmost bin:
data.v[2,*]
       29.505841581750701
       40.459037597036343
       51.412233612321984
       66.951229863790203
       84.284348335260177
       101.98356599473314
       118.90628602312793
       133.28637701642214
       141.59113061604293
       149.89588421566373
data.y[2,*]
                      NaN
       0.0000000000000000
       0.0000000000000000
       0.0000000000000000
       427.21808553632405
       0.0000000000000000
       0.0000000000000000
       0.0000000000000000
       0.0000000000000000
                      NaN
idl use the average of (66.9, 84.28) as the upper boundary, and the average of (84.28,101.98) as the lower boundary. Is python tplot behaving similarly?
<img width="1053" alt="PastedGraphic-3" src="https://github.com/spedas/pyspedas/assets/105754292/bf8dba8f-da2f-43ba-bff3-c2c14084c2e8">

**Comment by jameswilburlewis** [comment]
IDL code for this event:
tstart='2021-07-14/11:55'
tend='2021-07-14/12:05'

timeduration=time_double(tend)-time_double(tstart)
timespan,tstart,timeduration,/seconds

elf_load_state, probes=probe
elf_load_epd, probes=probe, level='l1'
elf_getspec
get_data,'ela_pef_pa_spec2plot_ch0', data=data, dlim=dlim, lim=lim
tplot,'ela_pef_pa_spec2plot_ch0'
tlimit,['2021-07-14/11:57:48','2021-07-14/12:00']


; closer look at the first 10 points
store_data,'data',data={x:data.x[0:10], y:data.y[0:10,1:8], v:data.v[0:10,1:8]}, dlim=dlim, lim=lim
tlimit,['2021-07-14/11:55:48','2021-07-14/11:56:03']

Python code (in elfin branch):

epd_var = 
pyspedas.elfin.epd(

trange=['2021-07-14/11:55',
'2021-07-14/12:05'],

probe='a',

level='l2',

type_='nflux',

fullspin=False)



time_clip('ela_pef_hs_nflux_ch0','2021-07-14/11:57:48','2021-07-14/12:00',
overwrite=True)

data =get_data('ela_pef_hs_nflux_ch0')

metadata=get_data('ela_pef_hs_nflux_ch0',
metadata=True)



# closer look at the first 10 points

store_data('data',
data={'x': data.times[0:11],
'y': data.y[0:11,1:9],
'v': data.v[0:11,1:9]},
attr_dict=get_data('ela_pef_hs_nflux_ch0',
metadata=True))

options('data',
'y_range', [0,
180])

tplot('data')

**Comment by jimm02** [comment]
Hi, 

I think that the Python program is using a V array that's been smoothed over time. The V values oscillate from spin to spin, so that the value for bin 4 (in python) oscillates between 77-78 degrees and 84-85. This shows up better on the IDL plot:
![elfin_test_idl](https://github.com/spedas/pyspedas/assets/124631823/994c0c6a-4b0d-43e5-a12b-89db9d724018)

The V bins look prettty consistent in the Pyspedas plot:
![elfin_test_Figure_1](https://github.com/spedas/pyspedas/assets/124631823/927e9d7a-81fa-48f2-b261-20d7d75f9fcc)

But the V bins do change slightly from time to time, for the next plot, I set yrange to [70, 75], 
pytplot.options('data','y_range',[70,75])
![elfin_test_Figure_2](https://github.com/spedas/pyspedas/assets/124631823/ee18b923-382b-44d1-bed9-d5f3fcfa3167)

On this plot, you can see the lower limit changing for the 5th and 6th data intervals. 

I'll look at this more tomorrow.

**Comment by jimm02** [comment]
Ok, I fixed  this by resampling along the Y axis. Resampling can be turned off using pytplot.options(var, 'y_no_resample', 1) and turned back on using pytplot.options(var,'y_no_resample',None) or pytplot.options(var,'y_no_resample',0).
![](http://sprg.ssl.berkeley.edu/~jimm/temp/Figure_specplot_fixed.png)
I'll close this when I figure out how to add this to tests directory.

**Comment by jimm02** [comment]
![](http://sprg.ssl.berkeley.edu/~jimm/temp/Figure_specplot_fixed.png)

**Comment by jimm02** [comment]
![Figure_specplot_fixed](https://github.com/spedas/pyspedas/assets/124631823/99726385-01cb-4a3d-a492-ad9cea610a8a)

**Comment by jiashuwu89** [comment]
Hi Jim,

Thanks for the updates. i got the latest pytplot from matplotlib-backend branch and saw your changes. however, i couldn't apply it correctly. 

```
epd_var = pyspedas.elfin.epd(
        trange=['2021-07-14/11:55', '2021-07-14/12:05'],
        probe='a',
        level='l2',
)
options('ela_pef_hs_nflux_ch0', 'y_no_resample', 1)
tplot('ela_pef_hs_nflux_ch0')

```
am i using it correctly? the figure still looks the same as before.

jiashu

**Comment by jimm02** [comment]
Hi Jiashu,
Resample is the default, so only set y_no_resample to 1 if you want the old behavior. In this case, do not use the options command:
epd_var = pyspedas.elfin.epd(
        trange=['2021-07-14/11:55', '2021-07-14/12:05'],
        probe='a',
        level='l2',
)
tplot('ela_pef_hs_nflux_ch0')
jm

**Comment by jiashuwu89** [comment]
Works great! pyspedas and spedas comparison.



![Image](https://github.com/spedas/pyspedas/assets/99274895/08483f87-46d9-4277-a482-4693a76f60f6)


Thanks for your help!
