### ISSUE TITLE
Request for RSBP ephemeris

### ISSUE THREAD

**Issue by PluckZK** [spedas/pyspedas#618]
Is it possible to add direct reads to RBSP ephemeris? 
Cdaweb provides RBSP position files(https://cdaweb.gsfc.nasa.gov/pub/data/rbsp/rbspb/ephemeris/). 
If users want to read only satellite positions, they can avoid downloading a lot of unused instrument data.

**Comment by PluckZK** [comment]
In fact, there is already IDL code to do this. [https://github.com/awbrenem/mission_routines/blob/3904f63859ac0b7b3c4f0e55bcc2eeb1ca87c7fc/rbsp_routines/rbsp_load_ephem_cdf.pro#L3](url)
 But we are still missing the python version.

**Comment by PluckZK** [comment]
In fact, there is already IDL code to do this. https://github.com/awbrenem/mission_routines/blob/3904f63859ac0b7b3c4f0e55bcc2eeb1ca87c7fc/rbsp_routines/rbsp_load_ephem_cdf.pro#L3
But we are still missing the python version.

**Comment by jameswilburlewis** [comment]
This data is now available via the pyspedas.rbsp.magephem() load routine.

**Comment by PluckZK** [comment]
It works, thanks a lot!
