### ISSUE TITLE
pyspedas equivalent to IDL libs command

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#629]
Users should be able to look up documentation by giving a routine name or keyword, and be able to see the path to the source code and header comments.  Some of this is probably available in the iDE but this gives a tool that will work the same everywhere.

Ideally, whatever database this tool uses should be populated automatically, during the release build process, or github actions, or something similar.

Wildcard support would be nice.

**Comment by xandrd** [comment]
Is `libs` command a part of SPEDAS? If yes, where is it located?

**Comment by jameswilburlewis** [comment]
THEMIS> *libs*,'libs'

% Compiled module: LIBS.

/Users/jwl/spdsoft_trunk/general/misc/system/libs.pro

THEMIS>


Cheers,


-- Jim

**Comment by xandrd** [comment]
@jameswilburlewis, thanks! I actually deleted the comment, because I was able to find it.
