### ISSUE TITLE
Specifying wsize in  tplot_options does not seem to work

### ISSUE THREAD

**Issue by nickssl** [spedas/pyspedas#646]
As the following example shows, specifying wsize (window size) in tplot_options does not seem to do anything, either for displaying the plot or for saving the file. On the other hand, xsize and ysize in tplot work, but the numbers are not in pixels but in hundreds of pixels. 

This might be an instance of a more general problem. Perhaps when pytplot changed from Qt and Bokeh to matplotlib, not all the parameters were implemented in the new version. 

Also, the documentation is probably not up to date, not all the matplotlib parameters are documented. For example:

In tplot_options.py the documentation says:
wsize             [int, int]   [height, width], pixel size of the plot window

In tplot.py, there is no documentation for xsize, ysize.

```
from pyspedas.themis import state
from pytplot import tplot_options, tplot


time_range = ["2015-12-31 00:00:00", "2016-01-01 12:00:00"]
state(probe="a", trange=time_range, time_clip=True)

# Specifying wsize doesn't seem to work.
filename = "c:\\work\\test"
tplot_options("wsize", [1000, 1400])
tplot(["tha_pos", "tha_vel"], save_png=filename)

# Specifying xsize, ysize directly, works for both display and saved file.
# However, the units are in 100s of pixels.
filename1 = "c:\\work\\test1"
tplot(["tha_pos", "tha_vel"], save_png=filename1, xsize=10.11, ysize=14.22)
```

**Comment by jameswilburlewis** [comment]
For matplotlib, xsize and ysize are in units of inches.  I made some changes to the MMS overview plots to reflect this. wsize is one of several tplot_options that doesn't seem to be implemented yet for matplotlib.  We'll have to go through them and see which ones make sense to keep.  I'll open a separate issue for that.
