### ISSUE TITLE
Obsolete pytplot documentation

### ISSUE THREAD

**Issue by nickssl** [spedas/pyspedas#649]
Documentation for pytplot is here:
https://pytplot.readthedocs.io/en/latest/plotting.html#tplot-function

However, this documentation is for the old Qt version and not for the new matplotlib version. This is probably confusing for pyspedas users, especially since a lot of plotting properties can only be specified using pytplot, and the options for matplotlib and Qt are not the same.

**Comment by jameswilburlewis** [comment]
Duplicate of https://github.com/spedas/pyspedas/issues/436
