### ISSUE TITLE
tdeflag feature request

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#658]
From Vassilis:

I noticed in pyspedas, tdeflag has an option ‘repeat’ and also to eliminate the NaNs but what it is most useful for is to do linear interpolation across gaps previously placed by tdegap and tclip. If not already included, could you please make that (method=‘linear’) the default?

 Also in the documentation it lists as the default suffix ‘-clip’ but I think it means ‘_deflag’ (is it an underscore as in tdegap)?

**Comment by jimm02** [comment]
Tdeflag is now in tplot_math, I fixed a problem with vector input crashing. Now tdeflag is a wrapper for deflag, but with 'linear' as the default option. (The default for deflag [no "t"] for now is to replace flagged values with NaN, to retain backwards compatibility.)

**Comment by jameswilburlewis** [comment]
The older pyspedas version of tdeflag had replace_nan as the default, and there were some tests that depended on that.  So I changed the pyspedas wrapper to default to replace_nan.  Once we've converted all the existing tdeflag calls to use the pytplot version, the.wrapper will go away, and there will only be one version of tdeflag that defaults to method="linear".
