### ISSUE TITLE
More pseudovariable issues

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#661]
I attach a plot and an associated crib sheet. The crib sheet ends where it is noted in a comment (ENDS HERE). Just above it the plot is produced by a call to tplot. You can view or run in command line.

 The issues I see is that the options: ‘ytitle’ and ‘ysubtitle’ (as marked) as well as ‘ylog’ (not shown) do not work for the pseudovariable that contains spectra: 'des_eflux_omni_fast_wscpot'. I may have reported this before. (However these work for scalar pseudovariables as 'dxs_Tparper_fast' above it.)

 Another issue that I see (not previously reported) is that when I define a plot title using tplot_options(‘title’,’MMS3_Overview’), that title appears 4 times in the plot, once correctly at the top and 3 other times incorrectly above each pseudovariable.

 These are of less importance, though. The most important thing to fix remains the ability to change colors in scalar pseudovariables, a critical means to compare scientific quantities produced by different methods.

![mms_ovr_BE_FPImoms](https://github.com/spedas/pyspedas/assets/105754292/abadaa67-ca14-4dba-ae36-097479d4b8c8)

**Comment by nickssl** [comment]
The file mms_overview_plot.py shows how to resolve some of these issues.

To avoid the multiple titles, use:
options(panel01, "name", "")

For line colors, use:
options(panel01, "Color", ["black", "green"])

The following seem to work correctly:

options(panel01, "name", "")
options(panel01, "Color", ["black", "green"])
options(panel01, "legend_names", ["Themis AE", "Kyoto proxy AE"])
options(panel01, "ytitle", "AE Intex")
options(panel01, "ysubtitle", "[nt]")
options(panel01, "legend_location", "spedas")

**Comment by nickssl** [comment]
There are two related bugs:

The following produces a legend which is partially hidden, because the width of the plot is not computed correctly:
options(panel01, "legend_location", "spedas")
See also: https://github.com/spedas/pyspedas/issues/641

The second problem is that  store_data crashes when it is used with two tplot variables and one of them does not exist. IDL handles this correctly. Example:
store_data(panel01, data=[d1_1, d1_2])

**Comment by jameswilburlewis** [comment]
More concise code to reproduce the multiple plot titles:

```
import pyspedas
from pytplot import store_data,tplot,tplot_options
pyspedas.themis.state()
store_data('ps1',['thc_spin_initial_delta_phi','thc_spin_idpu_spinper'])
store_data('ps2',['thc_spin_initial_delta_phi','thc_spin_idpu_spinper'])
store_data('ps3',['thc_spin_initial_delta_phi','thc_spin_idpu_spinper'])
tplot_options('title','plot title')
plotvars=['thc_pos', 'ps1', 'thc_vel', 'ps2', 'thc_pos_gse', 'ps3']
tplot(plotvars)


```

**Comment by jameswilburlewis** [comment]
See also: https://github.com/spedas/pyspedas/issues/796 for problems combining line plots with different numbers of traces.

**Comment by jameswilburlewis** [comment]
The multiple plot titles are fixed now.   The other problems have been filed as separate issues, so this one can be closed.
