### ISSUE TITLE
Request for cdaweb GOES data interface

### ISSUE THREAD

**Issue by PluckZK** [spedas/pyspedas#665]
The magnetic field data from the NOAA source(https://data.ngdc.noaa.gov/platforms/solar-space-observing-satellites/goes/) is not transferred to the geomagnetic coordinate system, which is not convenient to use. 

However, the .nc file in the GOES directory of cdaweb(https://cdaweb.gsfc.nasa.gov/pub/data/goes/goes15/mag_l2_netcdf/) provides the magnetic field in the GSM coordinate system. 

Is it possible to add a download interface for the GOES satellite from cdaweb?

Thank you very much!

**Comment by jameswilburlewis** [comment]
We already have a CDAWeb load interface which lets you download the GOES netcdf files from CDAWeb, but it's trying to load them as CDFs, and failing.  That should be an easy fix.  I'll also adjust the pyspedas imports so the cdaweb load routine is easier to get to (right now you have to do something like  "from pyspedas.cdagui.cdagui import cdagui").

**Comment by nickssl** [comment]
Added the ability to load netcdf files. 

See: https://github.com/spedas/pyspedas/pull/672

**Comment by PluckZK** [comment]
Thank you very much! 💯
