### ISSUE TITLE
Need a routine to load Kp index data

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#677]
We'll want to be able to load Kp index values for the T89 field model.

In IDL SPEDAS, we have noaa_load_kp, but that seems to be broken at the moment -- perhaps NOAA has changed the layout of their FTP directories.

**Comment by jameswilburlewis** [comment]
There is an alternate source for data after 2018: ftp://ftp.gfz-potsdam.de/pub/home/obs/kp-ap/wdc/.  noaa_load_kp uses this server if the /gfz keyword is set.  We should update noaa_load_kp to default to that site for end dates after the 2018 cutoff before porting it to Python.

**Comment by jameswilburlewis** [comment]
Updates to IDL noaa_load_kp are implemented, still need to port to Python.

**Comment by nickssl** [comment]
Updates to IDL noaa_load_kp have been implemented.

Still needs to be ported to Python.

The pyspedas download function cannot be used with FTP, a new function was created pyspedas.utilities.download_ftp

**Comment by nickssl** [comment]
Added the function utilities.download_ftp for downloading files from FTP sites.

Added noaa.noaa_load_kp. The directory is called "noaa" because that's how the IDL directory is called. 

Added README.md in the noaa folder, with extensive explanation of what the downloaded files contain, including the format. See:
https://github.com/spedas/pyspedas/tree/master/pyspedas/noaa

**Comment by jameswilburlewis** [comment]
I had a problem running the example in the README.md file:

```
from pyspedas.noaa.noaa_load_kp import noaa_load_kp
trange = ["2017-03-23/00:00:00", "2017-04-23/23:59:59"]
vars = noaa_load_kp(trange=trange)
18-Jan-24 20:47:56: Loading geomagnetic index data from ftp.ngdc.noaa.gov/STP/GEOMAGNETIC_DATA/INDICES/KP_AP/
18-Jan-24 20:47:57: [Errno 2] No such file or directory: 'geom_indices/2017'
18-Jan-24 20:47:57: No files found.

```

Also, there was a problem building the latest release on github:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/runner/work/pyspedas/pyspedas/pyspedas/__init__.py", line 76, in <module>
    from .noaa import noaa_load_kp
  File "/home/runner/work/pyspedas/pyspedas/pyspedas/noaa/__init__.py", line 1, in <module>
    from .noaa_load_kp import noaa_load_kp
  File "/home/runner/work/pyspedas/pyspedas/pyspedas/noaa/noaa_load_kp.py", line 45, in <module>
    def convert_to_float_or_int(a: list[str], outtype="int"):
TypeError: 'type' object is not subscriptable
Error: Process completed with exit code 1.
```

I'm using Python 3.9 and didn't have any problem with the imports, but the github build and testing is using Python 3.8.  I think I've seen this exact issue before:  https://github.com/spedas/pyspedas/issues/457

It should be pretty straightforward to implement the same fix...here's the commit for the previous fix: https://github.com/spedas/pyspedas/commit/4c40058f9797728a1fb2d703020395cbe4a73f21

**Comment by nickssl** [comment]
1. The first was a bug. Function download_ftp needs to explicitly create the local directory if it doesn't exist. It should be fixed now. 

2. For the second, this particular "type hint" for the vars array is not really helpful here, so I just removed it. I was using python 3.11.7 to test the function and with that version it worked fine but, as you suggested, earlier python versions need modifications to use type hints. 

Hopefully, it will all work correctly now!

**Comment by jameswilburlewis** [comment]
Looks great now, thanks!
