### ISSUE TITLE
Move load routines out of __init__.py files

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#685]
Most of our mission directories have load routines defined in the `__init__.py` file for each module.  This can be confusing, because  the source code isn't in the obvious place `load_whatever.py`.   I don't think there's any compelling reason to have them structured this way, and it's not generally considered to be a Python best practice, so we should probably start moving these routines into their own files, and replacing the function definitions with appropriate imports.

**Comment by nickssl** [comment]
See also: https://github.com/spedas/pyspedas/issues/730

**Comment by jameswilburlewis** [comment]
Superceded by https://github.com/spedas/pyspedas/issues/946
