### ISSUE TITLE
Load routine documentation: ace akebono barrel cluster cnofs csswe

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#690]
- [ ] Update docstrings for all load routines defined in the above directories, including those in` __init__.py`.  For preferred style and elements to be included, see https://spedas.org/wiki/index.php?title=PySPEDAS_docstring_format
- [ ] Update or add README.md files in each directory, ensuring all load routines are documented
- [ ] Ensure docstrings include example imports/calls (often can be found in README.md files)

If you find something that's not working, or if it's unclear how to document, please open a new iissue, then keep going with the next routine.  We'll come back and pick up any stragglers in another pass; the idea here is to get all the low-hanging fruit as quickly as possible.

**Comment by jiashuwu89** [comment]
notes for docstring task:
1. for each defined parameters, make sure default value is included in the docstring. See the last line in the following example:
"""
trange: list of str
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;time range of interest [starttime, endtime] with the format
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;['YYYY-MM-DD','YYYY-MM-DD'] or to specify more or less than a day
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;['YYYY-MM-DD/hh:mm:ss','YYYY-MM-DD/hh:mm:ss']
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Default: ['2007-03-23', '2007-03-24']**
"""

2. Examples should include import of packages, for example:
    `>>> import pyspedas`
    `>>> from pytplot import tplot`
3. The first description of function should includes the name of mission. for example:
"""
This function loads data from the **ACE** Electron Proton Alpha Monitor (EPAM)
"""

**Comment by jiashuwu89** [comment]
BARREL doesn't have a docstring. i have trouble adding the docstring. For example, what options are available for 'probe' parameter?
