### ISSUE TITLE
Load routine documentation: omni poes polar psp rbsp secs

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#695]
- [ ] Update docstrings for all load routines defined in the above directories, including those in` __init__.py`.  For preferred style and elements to be included, see https://spedas.org/wiki/index.php?title=PySPEDAS_docstring_format
- [ ] Update or add README.md files in each directory, ensuring all load routines are documented
- [ ] Ensure docstrings include example imports/calls (often can be found in README.md files)

If you find something that's not working, or if it's unclear how to document, please open a new iissue, then keep going with the next routine.  We'll come back and pick up any stragglers in another pass; the idea here is to get all the low-hanging fruit as quickly as possible.

**Comment by xandrd** [comment]
@jameswilburlewis  Would it be possible to exchange my assignment to this one? I am more familiar with omin and rbsp. I can also work with poes, noaa, goes, kyoto, lanl.

**Comment by jameswilburlewis** [comment]
No problem, but first let's see how far Jim M has been able to get....      Nick may have already made progress on goes, kyoto, etc., but maybe he'll be willing to swap if there are some he hasn't started yet.
