### ISSUE TITLE
Add no_download key to omni_load_data routine

### ISSUE THREAD

**Issue by clrussell90404** [spedas/pyspedas#718]
Colin Wilkins requested a no_download keyword be added to the omni_load_data routine. Sometimes downloading omni data can take a long time and he wanted to be able to use a local file. In addition, he requested a local_file_first keyword be added so that the load routine would look for a local file first before trying to download.

**Comment by jameswilburlewis** [comment]
I think this was actually an IDL SPEDAS request, which appears to have been implemented
