### ISSUE TITLE
No varnames keyword in rbsp

### ISSUE THREAD

**Issue by donglai96** [spedas/pyspedas#73]
Currently there is no 'varname' keyword in rept load file, don't know why
def load(trange=['2018-11-5', '2018-11-6'], 
         probe='a',
         instrument='emfisis', 
         level='l3',
         datatype='magnetometer', 
         suffix='', 
         cadence='4sec', # for EMFISIS mag data
         coord='sm', # for EMFISIS mag data
         rel='rel04', # for ECT data
         get_support_data=False, 
         varformat=None,
         downloadonly=False,
         notplot=False,
         no_update=False,
         time_clip=False):

**Comment by supervised** [comment]
Thanks for reporting this! I think THEMIS is the only mission that currently supports varnames; I'll update the rest of the load routines to support this keyword this week.

**Comment by supervised** [comment]
This should be fixed now (though the option is 'varnames'), e.g., 

```
import pyspedas
pyspedas.rbsp.emfisis(varnames=['Mag'])
```

**Comment by donglai96** [comment]
Thank you so much,
