### ISSUE TITLE
Redundant and confusing functions inside  __init__.py files

### ISSUE THREAD

**Issue by nickssl** [spedas/pyspedas#730]
The __init__.py files in most directories contain functions that are duplicate and unnecessary. In my opinion, these functions are more confusing than helping the users. They also slow down loading pyspedas, because when we use "import pyspedas" the system runs all these __init__.py files.

One example. For the "image" mission, data for the LENA instrument can be loaded as:

```
pyspedas.image.load(trange=trange, instrument="lena")
```

For the MENA instrument, it can be loaded as:

```
pyspedas.image.load(trange=trange, instrument="mena")
```

The above functions can always be used, but we also have the __init__.py file which contains 440 lines, and defines 7 new load functions that all call the above load function (which is defined in a different file). So, we are adding 7 alternative functions like the following:

```
pyspedas.image.lena(trange=trange)
```
```
pyspedas.image.mena(trange=trange)
```

This does save typing a couple of words, but creates redundant functions and in my opinion, it is confusing for the users because there are now two different ways to do exactly the same thing. 

Also, since we have 7 new functions, we also have 7 new docstrings, that repeat exactly the same thing as the load function docstring but for a different instrument. Please have a look at the __init__.py file and the docstrings it contains. It is basically the same string which is repeated 7 times. They all call the same function, which again has practically the same docstring.  

https://github.com/spedas/pyspedas/blob/master/pyspedas/image/__init__.py

In my opinion, this is not useful. We should remove all these duplicate functions and leave the __init__.py file mostly empty. All missions can load data using the same format:

```
 pyspedas.mission.load() 
```

which we already have. We do not need additional loading functions. 

Removing these redundant functions will make pyspedas more uniform and easier to understand for new users.

**Comment by jameswilburlewis** [comment]
I agree!  See: https://github.com/spedas/pyspedas/issues/685

**Comment by nickssl** [comment]
Also, my opinion is that we should add a system wide load() function that can call the load functions for multiple missions like this:

```
pyspedas.load(mission=["array of missions"])
```

This will make loading data from different missions for the same time range much easier than it is now. 

This is the opposite of what we are doing now with the __init__ files.

**Comment by nickssl** [comment]
> I agree! See: #685

I forgot that task. Anyway, I think it is better if we just remove these additional functions, rather than create a new file for each one of them. 

For example, for the "IMAGE" mission above, if we create 7 new files, we are creating a lot of redundant information. The documentation will contain 7+1 different load functions when we actually need one. It will be confusing, especially for someone who doesn't really look into the functions to see that they are all calling the same (only one) load() function. 

Extrapolating to the full project, we have 37 directories, if each of them contains 5 redundant load functions, the total is over 185 functions (or files) that have full documentation ... while none of them is actually needed!

**Comment by nickssl** [comment]
One solution is to replace all the duplicate functions with alias. I did this for GOES. Previously, the __init__.py file had 765 lines including duplicate documentation, now it is only 18 lines.

https://github.com/spedas/pyspedas/blob/master/pyspedas/goes/__init__.py

1. If the alias function is an exact duplicate, in python we can simply use the equality which works for functions. For example:

```python
orbit = load_orbit
```

2. If there are a few parameters specified, we specify an alias using using functools.partial. Examples:

```python
from functools import partial

fgm = partial(load, instrument="fgm")
eps = partial(load, instrument="eps")
epead = partial(load, instrument="epead")
```

**Comment by nickssl** [comment]
Defining alias for duplicate functions resolves some problems, for example the problem of redundant docstrings. 

However, my opinion is that these functions are still duplicate and unnecessary and should be removed altogether. It is better if we make pyspedas uniform and have a single "load()" function for every mission and simply use something like the following for any mission:

```python
pyspedas.mission.load()
```

In IDL, we cannot use the same name for two different functions so all load functions are different. However, python does not have this limitation. So, we can have load.py files and load() functions in different directories, for example:  

```
pyspedas\goes\load.py
pyspedas\mms\load.py
pyspedas\themis\load.py
```

Already, most of the load functions are like this, but not all of them. My opinion is that we should make this uniform for all missions, changing the names of any functions and files that are different.

**Comment by nickssl** [comment]
Summary: 

In IDL spedas, there are dozens of different load functions both for the same mission and for different missions. The reasons are:

1. Historical, since many of these functions were developed by separate teams. 
2. A limitation of IDL, which does not have namespaces and does not allow multiple functions with the same name.

In pyspedas, we can either:

1. Follow IDL spedas and have dozens of loading functions (or alias) with the same names as in IDL.
2. Simplify the code and have a single load() function for every mission (with almost the same parameters - trange, probe, instrument etc).

**Comment by Beforerr** [comment]
I would vote for the first option since this is more general and works for more complicate workflow when using multiple missions with multiple instruments.

Also a good reference for implementation is `spz.get_data` in [speasy](https://github.com/SciQLop/speasy), which is very general and powerful.

And it would be nice to incorporate `speasy` into pyspedas system, which provides a lot of benefits (cache, downloading speed, flexible configuration) in regards of downloading data.

**Comment by nickssl** [comment]
In python, one simple way to send different parameters to the load() function is by using a dictionary parameter (extra). This way, the signature of the load() function remains the same, but it is still highly customizable.

**Comment by jameswilburlewis** [comment]
Superceded by https://github.com/spedas/pyspedas/issues/946.  It may be now be feasible to address some of the other issues with tools like pyspedas.utilities.pyspedas_functools that can simplify our code without breaking our documentation or sacrificing IDE features like code autocompletion.  We'll address those in a future issue.
