### ISSUE TITLE
Reprocess all gmag stack plots

### ISSUE THREAD

**Issue by clrussell90404** [spedas/pyspedas#731]
Autumnx is downloading now. The mag stack plots (all, low, and hi lat) need to be reprocessed starting on 2023-09-15 to present. 
We are still waiting for older missed data (2023-09-15 to 2023-12-20).

**Comment by jameswilburlewis** [comment]
On hold until the autumnx data server issues are resolved.

**Comment by clrussell90404** [comment]
AUTUMNX data has not been recovered and negotiations with UCalgary are ongoing. The list of mid/low lat stations, however, has been updated to include many of the new networks that have locations that meet our criteria. The stack plots have been reprocessed to include these new stations. If and when AUTUMNX data becomes available this can be readdressed. For now, the situation has been resolved.
