### ISSUE TITLE
Support direct dataset loading

### ISSUE THREAD

**Issue by Beforerr** [spedas/pyspedas#770]
For example, `magplasma` dataset for STEREO is located in CDAWEB with link `https://spdf.gsfc.nasa.gov/pub/data/stereo/ahead/l2/impact/magplasma/1min/` and it could not be loaded by `stereo` module right now.

Right now PySPEDAS loading logic is like `mission->instrument->datatype&level` it would be nice to directly support loading dataset with logic like `mission->dataset` for dataset combined from multiple instrument. Also it might be possible that some dataset combine multiple mission, then the logic would be like `dataset -> ... `.

**Comment by Beforerr** [comment]
Another idea is to make a dataframe/table to match keyword to remote file link. So the user could specify some keyword to uniquely match the remote link (fuzzy matching might be useful also)

```
| dataset | mission | instrument | level | doi | spase id | other keywords | remote link| 
...
```

**Comment by jameswilburlewis** [comment]
It is probably going to be impossible to implement a completely mission-independent load routine -- there is no standard way of organizing the data download directory hierarchies, or of naming the individual files given a set of components {dataset, mission, instrument, level,...}.   Every mission seems to do it slightly differently, and it's not even guaranteed to be consistent from instrument to instrument on the same mission.  So any potential solution would need to replicate much of what's already been implemented in the mission-specific load routines.   There might be room for some marginal improvement here and there, but I don't think a major rewrite would be worth the effort.

**Comment by Beforerr** [comment]
@jameswilburlewis  this table does not need to standardize the way of organizing the data download directory hierarchies. It is more like a listing the infos in a language-agnostic way. So it provides more contexta and make it easier to update with new datasets.

**Comment by Beforerr** [comment]
Also it would be nice to support loading datasets like `https://spdf.gsfc.nasa.gov/pub/data/stereo/ahead/l2/impact/magplasma/1min/` which combines data from mutliple instruments.
