### ISSUE TITLE
Master list for tplot documentation updates

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#783]
Here is the next batch of routines that need their docstrings checked and updated.   All parameters should be documented, with any default values called out, and any "multiple-choice" type parameters listed out in the docstrings (if practical).   For the ones that already have examples in the docstrings, please check to ensure that they still work;  if not, please add an example.  Type hints would also be nice...most of them should be fairly obvious.

I'll start with a few assignments -- as you finish a group, please check them off here, then claim a few more to work on by editing in your name on the routines you'll be working on next.

Pytplot/tplot_math:

- [x] add (Cindy)
- [x] add_across (Cindy)
- [x] avg_res_data (Cindy)
- [x] clean_spikes (Jim L)
- [x] clip (Cindy)
- [x] crop (Cindy)
- [x] deflag (Jim L)
- [x] degap (Nick)
- [x] derive (Jim L)
- [x] divide (Jim L)
- [x] dpwrspc (Nick)
- [x] examples (Nick)
- [x] flatten (Nick)
- [x] interp_nan (Nick)
- [x] join_vec (Nick)
- [x] makegap (Nick)
- [x] multiply (Nick)
- [x] pwr_spec (Nick)
- [x] pwrspc (Nick)
- [x] resample (Nick)
- [x] spec_mult (Cindy)
- [x] split_vec (Cindy)
- [x] subtract (Cindy)
- [x] subtract_average (Cindy)
- [x] subtract_median (Cindy)
- [x] tcrossp (Cindy)
- [x] tdeflag (Cindy)
- [x] tdotp (Cindy)
- [x] tdpwrspc (Cindy)
- [x] time_clip (Cindy)
- [x] tinterp (Jiashu)
- [x] tkm2re (Jiashu)
- [x] tnormalize (Jiashu)
- [x] tpwrspc (Jiashu)
- [x] tsmooth (Jiashu)

Pytplot:

- [x] data_att_getters_setters (Jiashu)
- [x] data_exists (Jiashu)
- [x] del_data (Jiashu)
- [x] get_data (Jiashu)
- [x] get_timespan (Jiashu)
- [x] get_ylimits (Sasha)
- [x] link (Jim L)
- [x] options (Sasha)
- [x] replace_data (Nick)
- [x] replace_metadata (Nick)
- [x] spedas_colorbar (Nick)
- [x] store_data (Jim L)
- [x] time_double (Sasha)
- [x] time_string (Sasha)
- [x] timebar (Nick)
- [x] timespan (Nick)
- [x] timestamp (Jiashu)
- [x] tlimit (Jim L)
- [x] tnames (Jiashu)
- [x] tplot_copy (Jiashu)
- [x] tplot_names (Jiashu)
- [x] tplot_options (Jim L)
- [x] tplot_rename (Jiashu)
- [x] tplot_utilities
- [x] tres 
- [x] xlim 
- [x] ylim 
- [x] zlim 

pyspedas/analysis:

- [x] avg_data (Jim L)
- [x] deriv_data (Jim L)
- [x] dpwrspc  (Cindy) 
- [x] find_magnetic_nulls (Jim L)
- [x] lingradest (Jim L)
- [x] neutral_sheet (Nick)
- [x] tdeflag (Jim L)
- [x] tdpwrspc (Cindy)
- [x] time_domain_filter (not needed)
- [x] tinterpol (Nick)
- [x] tvectot (Jim L)
- [x] twavpol (Jim L)
- [x] wavelet (Cindy)
- [x] yclip (Nick)

pyspedas/utilities

- [x] dailynames (Cindy)
- [x] datasets
- [x] download (Nick)
- [x] download_ftp (Nick)
- [x] interpol (Cindy)
- [x] leap_seconds
- [x] libs 
- [x] mpause_2 (Jim L)
- [x] mpause_t96 (Jim L)
- [x] tcopy (Jiashu)

**Comment by clrussell90404** [comment]
Hi Jim,

My version of pyspedas on pycharm only has pyspedas project files. How do I access Pytplot/tplot_math using pycharm and girhub?

Thanks,

Cindy

________________________________
From: Jim Lewis ***@***.***>
Sent: Friday, March 1, 2024 4:49 PM
To: spedas/pyspedas ***@***.***>
Cc: Russell, Cindy ***@***.***>; Assign ***@***.***>
Subject: [spedas/pyspedas] Master list for tplot documentation updates (Issue #783)


Here is the next batch of routines that need their docstrings checked and updated. All parameters should be documented, with any default values called out, and any "multiple-choice" type parameters listed out in the docstrings (if practical). For the ones that already have examples in the docstrings, please check to ensure that they still work; if not, please add an example. Type hints would also be nice...most of them should be fairly obvious.

I'll start with a few assignments -- as you finish a group, please check them off here, then claim a few more to work on by editing in your name on the routines you'll be working on next.

Pytplot/tplot_math:

  *    add (Jim L)
  *    add_across (Jim L)
  *    avg_res_data (Jim L)
  *    clean_spikes (Jim L)
  *    clip (Jim L)
  *    crop (Jim L)
  *    deflag (Jim L)
  *    degap (Jim L)
  *    derive (Jim L)
  *    divide (Jim L)
  *    dpwrspc (Nick)
  *    examples (Nick)
  *    flatten (Nick)
  *    interp_nan (Nick)
  *    join_vec (Nick)
  *    makegap (Nick)
  *    multiply (Nick)
  *    pwr_spec (Nick)
  *    pwrspc (Nick)
  *    resample (Nick)
  *    spec_mult (Cindy)
  *    split_vec (Cindy)
  *    subtract (Cindy)
  *    subtract_average (Cindy)
  *    subtract_median (Cindy)
  *    tcrossp (Cindy)
  *    tdeflag (Cindy)
  *    tdotp (Cindy)
  *    tdpwrspc (Cindy)
  *    time_clip (Cindy)
  *    tinterp (Jiashu)
  *    tkm2re (Jiashu)
  *    tnormalize (Jiashu)
  *    tpwrspc (Jiashu)
  *    tsmooth (Jiashu)

Pytplot:

  *    data_att_getters_setters (Jiashu)
  *    data_exists (Jiashu)
  *    del_data (Jiashu)
  *    get_data (Jiashu)
  *    get_timespan (Jiashu)
  *    get_ylimits (Sasha)
  *    link (Sasha)
  *    options (Sasha)
  *    replace_data (Sasha)
  *    replace_metadata (Sasha)
  *    spedas_colorbar (Sasha)
  *    store_data (Sasha)
  *    time_double (Sasha)
  *    time_string (Sasha)
  *    timebar (Sasha)
  *    timespan (Sasha)
  *    timestamp
  *    tlimit
  *    tnames
  *    tplot_copy
  *    tplot_names
  *    tplot_options
  *    tplot_rename
  *    tplot_utilities
  *    tres
  *    xlim
  *    ylim
  *    zlim

pyspedas/analysis:

  *    avg_data
  *    deriv_data
  *    dpwrspc
  *    find_magnetic_nulls
  *    lingradest
  *    neutral_sheet
  *    tdeflag
  *    tdpwrspc
  *    time_domain_filter
  *    tinterpol
  *    tvectot
  *    twavpol
  *    wavelet
  *    yclip

pyspedas/utilities

  *    dailynames
  *    datasets
  *    download
  *    download_ftp
  *    interpol
  *    leap_seconds
  *    libs
  *    mpause_2
  *    mpause_t96
  *    tcopy

**Comment by jameswilburlewis** [comment]
The PyTplot code is in a different repository, under MAVENSDC.   I've just sent out invitations to all of you who aren't already collaborators on the PyTplot repo, so once you accept the invite, you should be able to push your changes directly instead of doing pull requests.

I would recommend setting PyTplot up as a separate Pycharm project, with its own virtual environment.   You can do that by closing any open Pycharm projects -- when you close the last one, it should take you to an "open project" dialog with "Get from VCS" as one of the options.  Click on that, then on the next panel there should be an option for Github.  Click on that -- it will probably populate the right pane with the SPEDAS repositories, but MAVENSDC/PyTplot may or may not be there.   If not, type it into the search bar at the top, and it should show up in the list underneath where you can select it.  Then click the "Clone" button to start setting up the new project, the same way you did for pyspedas.

Once the environment is set up, there's a very important step -- be sure you're working in the "matplotlib-backend" branch!
Click on "Git->Branches...",   and under the "remote branches" list, click on "matplotlib-backend', then "Checkout" from the options it gives.   That should switch your local copy to the correct branch.

For testing purposes, you may want to install pyspedas in your PyTplot environment with "pip install pyspedas" using the PyCharm terminal window.

**Comment by nickssl** [comment]
I removed the file tplot_math/examples.py.

This file contained some examples for an early version of pytplot, that are not useful any more. Most examples either used pytplot.data_quants directly (which should be avoided) or did not work because they called functions that do not exist anymore.
