### ISSUE TITLE
Request for NOAA source for POES

### ISSUE THREAD

**Issue by PluckZK** [spedas/pyspedas#785]
Compared with NOAA official, the current poes data on cdaweb is missing some parts. For example, noaa15 does not have data before 2013. Is it possible to add an official data source for POES?

https://www.ncei.noaa.gov/data/poes-metop-space-environment-monitor/access/l2/v01r00/cdf/

**Comment by jameswilburlewis** [comment]
Thanks, we'll take a look and see if we can make the NOAA version of the data available with SPEDAS and PySPEDAS.

**Comment by PluckZK** [comment]
> Thanks, we'll take a look and see if we can make the NOAA version of the data available with SPEDAS and PySPEDAS.

Thank you very much!

**Comment by nickssl** [comment]
Added keyword ncei_server, both for pyspedas and IDL spedas.

**Comment by PluckZK** [comment]
It works, thanks a lot!
