### ISSUE TITLE
pytplot docstring issues: tinterp tpwrspec, import pyspedas, get and get_data

### ISSUE THREAD

**Issue by jiashuwu89** [spedas/pyspedas#786]
# tinterp

The current docstring shows tvar2 is the one to interpolate: 
```
tvar1 : str
            Name of first tplot variable whose times will be used to interpolate tvar2's data.
tvar2 : str
            Name of second tplot variable whose data will be interpolated.
```

But the what the code does is interpolating the tvar1 and return

`return tvar1 + '_tinterp'`

I just want to confirm that tvar1 is the one we want to interpolate? Is that consistent with IDL func?

# tpwrspec
I couldn't find a runnable example for tpwrspec. I create something like this:
```
pytplot.store_data('a', data={'x':[1, 2, 3, 4, 5, 6, 7, 8, 9], 'y':[0, 0.64, 0.98, 0.86, 0.34, -0.34, -0.86, -0.98, -0.64]})
pytplot.tpwrspc('a')
```
whichi is some points of a sine wave. But runs into an error. should i import pyspedas and load some actual data as an example?

**Comment by jiashuwu89** [comment]
tpwrspc needs data longer than just 10 points. The following example works:

```
        >>> import pytplot
        >>> import numpy as np
        >>> pytplot.store_data('a', data={'x': range(100), 'y': np.random.random(100)})
        >>> pytplot.get_data('a_pwrspc')
```

**Is it ok if i import numpy package in the example?**

**Comment by jiashuwu89** [comment]
# issues when trying to import pyspedas

pyspedas 1.5.6 is installed. But when i was trying to import pyspedas to provide some examples, it shows:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jiashu/Documents/VScode/PyTplot/venv/lib/python3.9/site-packages/pyspedas/__init__.py", line 15, in <module>
    from .cdagui.cdagui import cdagui
  File "/Users/jiashu/Documents/VScode/PyTplot/venv/lib/python3.9/site-packages/pyspedas/cdagui/cdagui.py", line 21, in <module>
    import tkinter as tk
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

**Comment by jameswilburlewis** [comment]
It seems that the version of Python you're using in that environment wasn't built with Tk support.  Maybe the answers on the StackOverflow question will help: https://stackoverflow.com/questions/76105218/why-does-tkinter-or-turtle-seem-to-be-missing-or-broken-shouldnt-it-be-part

**Comment by jiashuwu89** [comment]
# get_data and get
Why is there a get func as a wrapper of get_data func?

**Comment by jameswilburlewis** [comment]
It looks like the only difference between get() and get_data() is that get() defaults to units=True.     There is also store() and store_data(), which appear to be identical.   I think we'll probably remove get() and store() and just add units=True where needed. See: https://github.com/spedas/pyspedas/issues/633

**Comment by jiashuwu89** [comment]
# get_any and set_any are not imported in the __init__.py
Should I import them? 
change
`from .data_att_getters_setters import set_coords, get_coords, set_units, get_units
`
to
`from .data_att_getters_setters import set_coords, get_coords, set_units, get_units, get_any, set_any`

**Comment by jameswilburlewis** [comment]
get_any and set_any are helper routines, not meant to be called from outside that module, so they shouldn't be imported into __init__.py .
