### ISSUE TITLE
Request for add 'ssc' instrument for THEMIS

### ISSUE THREAD

**Issue by PluckZK** [spedas/pyspedas#789]
CDAWEB provide 'ssc' for users to get the position and the footpoint position of THEMIS, for example the 'L_VALUE' 'NorthBtrace_GEO_LON' variable in cdf and so on.
https://cdaweb.gsfc.nasa.gov/pub/data/themis/thd/ssc/

If the user wants to only obtain satellite position data, or wants to reduce the calculation and time overhead caused by trace field lines, it is necessary to add a data interface to 'ssc'.

**Comment by jameswilburlewis** [comment]
CDAWeb has ingested the long-term THEMS orbit predictions from SSCWeb and made them available in CDF format:

Hi Jim – as per your request from our last meeting.  I made CDF data set files from the predictive THEMIS data in SSCWeb, and ingested them into CDAWeb.

The data sets are public today:

THAPRED_OR_SSC: THEMIS-A Predicted Orbit parameters from SSCWeb - SSCWeb (SPDF/Goddard)
      [Available Time Range: 2008/07/18 00:30:00 - 2029/01/01 00:00:00]  [Info](https://cdaweb.gsfc.nasa.gov/misc/NotesT.html#THAPRED_OR_SSC)  [Metadata](https://cdaweb.gsfc.nasa.gov/pub/software/cdawlib/0SKELTABLES/thapred_or_ssc_00000000_v01.skt)
THBPRED_OR_SSC: THEMIS-B Predicted Orbit parameters from SSCWeb - SSCWeb (SPDF/Goddard)
      [Available Time Range: 2008/07/18 00:30:00 - 2029/01/01 00:00:00]  [Info](https://cdaweb.gsfc.nasa.gov/misc/NotesT.html#THBPRED_OR_SSC)  [Metadata](https://cdaweb.gsfc.nasa.gov/pub/software/cdawlib/0SKELTABLES/thbpred_or_ssc_00000000_v01.skt)
THCPRED_OR_SSC: THEMIS-C Predicted Orbit parameters from SSCWeb - SSCWeb (SPDF/Goddard)
      [Available Time Range: 2008/07/18 00:30:00 - 2029/01/01 00:00:00]  [Info](https://cdaweb.gsfc.nasa.gov/misc/NotesT.html#THCPRED_OR_SSC)  [Metadata](https://cdaweb.gsfc.nasa.gov/pub/software/cdawlib/0SKELTABLES/thcpred_or_ssc_00000000_v01.skt)
THDPRED_OR_SSC: THEMIS-D Predicted Orbit parameters from SSCWeb - SSCWeb (SPDF/Goddard)
      [Available Time Range: 2008/07/18 00:30:00 - 2029/01/01 00:00:00]  [Info](https://cdaweb.gsfc.nasa.gov/misc/NotesT.html#THDPRED_OR_SSC)  [Metadata](https://cdaweb.gsfc.nasa.gov/pub/software/cdawlib/0SKELTABLES/thdpred_or_ssc_00000000_v01.skt)
THEPRED_OR_SSC: THEMIS-E Predicted Orbit parameters from SSCWeb - SSCWeb (SPDF/Goddard)
      [Available Time Range: 2008/07/18 00:30:00 - 2029/01/01 00:00:00]  [Info](https://cdaweb.gsfc.nasa.gov/misc/NotesT.html#THEPRED_OR_SSC)  [Metadata](https://cdaweb.gsfc.nasa.gov/pub/software/cdawlib/0SKELTABLES/thepred_or_ssc_00000000_v01.skt)

Sample URL for predicted orbit data:

https://spdf.gsfc.nasa.gov/pub/data/themis/tha/ssc_pre/2028/thapred_or_ssc_20280101_v01.cdf
(These files appear to contain one year of data per file)


The current/past orbit data from SSCWeb have been available for a while now, sample URL:
https://spdf.gsfc.nasa.gov/pub/data/themis/tha/ssc/2024/tha_or_ssc_20240801_v01.cdf
(One month of data per file)

**Comment by nickssl** [comment]
It is now available for pyspedas:

from pyspedas.themis import ssc (for current/past orbit data)
from pyspedas.themis import ssc_pre (for predicted)

IDL spedas is next.

**Comment by nickssl** [comment]
IDL spedas procedure is now available.

Examples:
themis_load_ssc, trange = ['2026-01-01', '2026-01-10'], probes=['a','b','c'], /predicted
themis_load_ssc, trange = ['2016-01-01', '2016-01-10'], probes='e'
