### ISSUE TITLE
Double suffixes when saving plots as png, eps, etc

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#802]
In tplot we have:

```
    if save_png is not None and save_png != '':
        plt.savefig(save_png + '.png', dpi=dpi)
```

and similar for other output formats.  We should check whether there's already a suffix before adding '.png' or whatever, to avoid filenames like myplot.png.png.

**Comment by nickssl** [comment]
The same problem appears in pyspedas:

mms_orbit_plot.py
mms_fpi_and_ang.py (this is somewhat different)
slice2d_plot.py

**Comment by nickssl** [comment]
Fixed.
