### ISSUE TITLE
line_dash is not implemented for matplotlib

### ISSUE THREAD

**Issue by nickssl** [spedas/pyspedas#833]
In pytplot, timebar.py defines a variable 'dash', which currently does not do anything. Perhaps it is not implemented yet in the matplotlib version of pytplot.

**Comment by jameswilburlewis** [comment]
Fixed in pytplot-mpl-temp version 2.2.49.  At some point, we may want to replace the 'dash' boolean with a 'linestyle' argument, which could support the full range of matplotlib line styles.
