### ISSUE TITLE
RBSP emfisis file loading does not work for density data

### ISSUE THREAD

**Issue by kaltensi** [spedas/pyspedas#85]
The code in RBSP load.py that creates the index string for the file to be loaded uses the same format for all emfisis files. However, while the datatype = magnetometer (level = l3) data can be loaded, the datatype = density ( level = l4) cannot. The index for the density data does not use cadence or coord, so calling pyspedas.rbp.emfisis(...) fails to load in the file even if all of the parameters are right. It should probably instead have another nested if statement, like it already does for the hope data.

Thanks.

**Comment by supervised** [comment]
Thanks for the bug report! this should be fixed now:

https://github.com/spedas/pyspedas/commit/3810f112888857b2f606e941a56df953cc4e6ecc
