### ISSUE TITLE
Loading data via CDAWeb doesn't seem to load full data set

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#862]
From Nick Gross on helionauts:

> I am continuing to use the PySPEDAS tools for looking at Voyager data. I wanted to look at time sequences over time scale of years. After setting the start and stop times, when using and getting the url list
> 
> `urllist = cdaweb_obj.get_filenames([dataset],start_time, end_time)`
> 
> 
> I use
> 
> `cdaweb_obj.cda_download(urllist,"cdaweb/",prefix='v2_')`
> 
> While this seems to look at the whole list, it only seems to return the results from the last file, which is one months worth of data.
> 
> My work around (which I have not done yet) is to loop through the ‘urllist’ array and load up each month one at a time and append the results I want to a new variable, but this will take me outside of the structures that are used by the PySPEDAS plotting tools.
> 

If we don't already have a unit test for cdaweb that returns and loads multiple files, we should add one.

**Comment by jameswilburlewis** [comment]
Here is the code Nick is running:


```
# Create the CDAWeb interface object
cdaweb_obj = pyspedas.CDAWeb()

# This mission and instrument are selected from the lists returned by
# the cdaweb_obj.get_observatories() and cdaweb.get_instruments() methods.
mission_list = ['Voyager']
instrument_list = ['Plasma and Solar Wind']

# Get a list of CDAWeb datasets for Voyager magnetometer data
dataset_list = cdaweb_obj.get_datasets(mission_list, instrument_list)
print(dataset_list)
# We'll pick one of available data sets and load it into tplot variables
dataset = 'VOYAGER2_COHO1HR_MERGED_MAG_PLASMA'
start_time = '2008-01-01 00:00:00'
end_time = '2010-01-01 00:00:00'

# Get the URLs for the available data in this time range
urllist = cdaweb_obj.get_filenames([dataset],start_time, end_time)

# Download the data and load as tplot variables.  Setting a prefix
# is useful if you want to work with both Voyager 1 and Voyager 2
# data; the variable names in the archived data are the same for both
# spacecraft.

cdaweb_obj.cda_download(urllist,"cdaweb/",prefix='v2_')
# Plot the data
tplot(['v2_protonDensity', 'v2_V'])
```

**Comment by nickssl** [comment]
This is now fixed. 
Previously, the cda_download() function did not have the keyword 'merge' and could load a single file only.
