### ISSUE TITLE
Typo on downloading GOES/EPEAD

### ISSUE THREAD

**Issue by zheyiding96** [spedas/pyspedas#874]
Please check  the  load.py in GOES,       "_epead_p17ew_1m_%Y%m01_%Y%m??.c", should be ".... .nc"
    if datatype == "1min":
                pathformat = [
                    "_epead_e13ew_1m_%Y%m01_%Y%m??.nc",
                    "_epead_p17ew_1m_%Y%m01_%Y%m??.c",
                    "_epead_a16ew_1m_%Y%m01_%Y%m??.nc",
                ]
                pathformat = [avg_path + s for s in pathformat]
            elif datatype == "5min" or datatype == "low":
                pathformat = [
                    "_epead_e13ew_5m_%Y%m01_%Y%m??.nc",
                    "_epead_p17ew_5m_%Y%m01_%Y%m??.c",
                    "_epead_a16ew_5m_%Y%m01_%Y%m??.nc",
                ]

**Comment by jameswilburlewis** [comment]
Thanks for finding that and letting us know!

**Comment by jameswilburlewis** [comment]
Fixed in pyspedas-1.5.14
