### ISSUE TITLE
Add load routines for Kyoto AE, AL, AU etc. indices

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#876]
We have a routine for the Kyoto Dst index,. but we should have routines to load the other indices also provided by the Kyoto WDC.

**Comment by jameswilburlewis** [comment]
It would be great if we had a top-level load routine "load_geomagnetic_indices", that takes the names of the various indices as the "datatypes" argument, then dispatches to the appropriate lower level load routines (kyoto, noaa, gfz, omni, etc) to load the requested data.  That way, the user won't have to keep track of which data provider offers which indices....

**Comment by nickssl** [comment]
I have now added the loading routine for the Kyoto AE indices.

**Comment by nickssl** [comment]
The Kyoto dst routine does not download a file. This should be modified to work in a similar way to the routine for Kyoto ae indices.

**Comment by nickssl** [comment]
Modified the Kyoto dst routine to download the data files (which are HTML pages with data in them). This required the addition of a new keyword ("text_only") to the pyspedas download() function because otherwise it would download a binary object.
