### ISSUE TITLE
Trouble Downloading RBSP EMFISIS WFR files

### ISSUE THREAD

**Issue by Stratuholic** [spedas/pyspedas#90]
Trying to download RBSP EMFISIS WFR data with pyspedas.
(remote path: https://spdf.gsfc.nasa.gov/pub/data/rbsp/rbspa/l2/emfisis/wfr/...)
However, the function pyspedas.rbsp.emfisis() seems not campatible. (as the data has neither 'cadence' nor 'coord')
The same problem seem to occur with HFR as well.
Maybe some special pathformat(similar to that of the datatype 'density') is required for HFR and WFR files, which has not been included in pyspedas yet.

**Comment by Stratuholic** [comment]
More: spinaverage of hope is not supported as well
I notice that the load.py for rbsp only supports datatype 'pitchangle' and 'moments' for instrument 'hope', which means level2 datatype 'spinaverage' isn't supported.
(remote path: https://spdf.gsfc.nasa.gov/pub/data/rbsp/rbspa/l2/ect/hope/spinaverage/...)
Seems much needs to be done for load.py

**Comment by jameswilburlewis** [comment]
These issues seem to be resolved now -- at least the test cases for HFR, WFR, and HOPE are passing with no apparent errors.
