### ISSUE TITLE
ELFIN test_state failing with differences in att_flag variable

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#900]
The test_state suite for ELFIN is failing due to the att_flag variable not matching what's in the archived data:

```
Mismatched elements: 11 / 11 (100%)
Max absolute difference: 1
Max relative difference: inf
 x: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)
 y: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

```

I've commented out that assertion for now, so we can have some coverage on the load routine.  Is the loaded data, or the archived data, the correct value?

**Comment by jiashuwu89** [comment]
att flag: interpolated=0, modeled=1. it should be different. we use modeled instead of interpolated right now. I think we can leave it commented out.
