### ISSUE TITLE
Support loading SECS data from CDAWeb

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#931]
We recently had a long outage on vmo.igpp.ucla.edu, which hosts the SECS and EICS data sets.  James Weigand says that this data is also available at CDAWeb, so we should add support for that with an spdf keyword.

**Comment by nickssl** [comment]
Where is the SECS data located? It is not in the main SPDF data directory:

https://spdf.gsfc.nasa.gov/pub/data/

Also, SECS is not in the list of missions of the CDAWeb GUI.

**Comment by jameswilburlewis** [comment]
I think it's here:

https://spdf.gsfc.nasa.gov/pub/data/aaa_special-purpose-datasets/spherical-elementary-and-equivalent-ionospheric-currents-weygand/

**Comment by nickssl** [comment]
Done.
