### ISSUE TITLE
Problem with downloading Solar Orbiter files

### ISSUE THREAD

**Issue by nsioulas** [spedas/pyspedas#94]
I was trying to use pyspedas to download SOLO files and got this warning:

module 'pyspedas' has no attribute 'solo'

* I am using the suggested routine

import pyspedas
rpw_vars = pyspedas.solo.rpw(trange=['2020-06-15', '2020-06-16'], datatype='hfr-surv')

**Comment by supervised** [comment]
Thanks for the bug report! 

Did you install pyspedas using pip? Solar Orbiter was only recently added (Dec 2020), so I suggest trying to update to the latest version of pyspedas with:

`pip install pyspedas --upgrade`

and checking that your version is 1.2.4 with:

`pip show pyspedas`

**Comment by nsioulas** [comment]
Problem solved! Thank you!
