### ISSUE TITLE
Refactor __init__.py files, add parameters to load routines

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#946]
The list of `__init__ .py` files below needs to be refactored.  Mainly, we want to move any function definitions out of `__init__.py` into their own files.  But as long as we're touching almost all the pyspedas load routines, we want to take this opportunity to add support for a few new load routine options: `prefix`, `suffix`, and `force_download`.

`prefix` and `suffix` are options to be passed to `cdf_to_tplot`, `netcdf_to_tplot`, and `sts_to_tplot`, and are applied to the tplot variable names loaded by each of those routines. Default values should be empty strings "".

`force_download` is an option to the `download()` routine in pyspedas/utilities/download.py.  It requests that any downloads happen unconditionally, even if the local file is newer than the remote file. Default value should be False.

It may happen that some missions bypass utilities/download.py -- if so, don't worry about implementing `force_download`, just move on.  

Some missions might use ASCII, CSV or other file formats, bypassing `cdf_to_tplot` and the other pytplot importers.  No need to handle `prefix` or `suffix` for these cases either, just move on and we'll come back to them later.

So, to summarize:  For each `__init__.py` file listed below:

1. Break it up into individual functions. (see comment below for a possibly helpful shell script for this), and "git add" the new files.  There shouldn't be any conflicting file names, but be careful just in case.
2. Replace the function definitions in `__init__.py` with imports from the newly created files.  
3. Do any other necessary adjustments of imports in the newly created files -- remove unneeded imports, add any other necessary imports (e.g. postprocessing routines that are now in separate files)
4. There is usually going to be a "master" load routine of some sort, that calls `download()`, `cdf_to_tplot()`, `netcdf_to_tplot()`, etc.  Add support for the `prefix`, `suffix`, and `force_download` parameters, and pass them through to `download()`, `cdf_to_tplot()`, etc.
5. Add support for `prefix`, `suffix`, and `force_download` to the individual load routines, and pass them through to the master load routine.
6. Add a comment near the top of each newly created individual file, mentioning the path to the `__init__.py` file it originally came from.  This will help if we ever need to look at the git history of that piece of code.
7. Update the docstrings for the master load routine and individual load routines with documentation for `prefix`, `suffix`, and `force_download`, for example:

    prefix : str, optional
        Prefix to add to the tplot variable names. Defaults to an empty string.
    suffix : str, optional
        Suffix to add to the tplot variable names. Defaults to an empty string.
    force_download : bool, optional
        If True, downloads the file even if a newer version exists locally. Default is False.

8. Run the test suite(s) and make sure everything still passes
9. Commit and push your changes, mark this directory finished, and claim another one if there are still any left to do.

And here's the master list, with initial assignments:

- [x] `./ace/__init__.py` (Jim L)
- [x] `./akebono/__init__.py` (Jim L)
- [x] `./barrel/__init__.py` (Jim L)
- [x] `./cluster/__init__.py` (Jim L)
- [x] `./cnofs/__init__.py` (Jim L)
- [x] `./csswe/__init__.py` (Jim L)
- [x] `./de2/__init__.py` (Nick)
- [x] `./dscovr/__init__.py` (Nick)
- [x] `./equator_s/__init__.py` (Nick) 
- [x] `./fast/__init__.py` (Nick)
- [x] `./geotail/__init__.py` (Cindy)
- [x] `./image/__init__.py` (Cindy)
- [x] `./lanl/__init__.py` (Sasha)
- [x] `./maven/__init__.py` (Cindy)
- [x] `./poes/__init__.py` (Sasha)
- [x] `./polar/__init__.py` (Jiashu)
- [x] `./psp/__init__.py` (Jiashu)
- [x] `./rbsp/__init__.py` (Sasha)
- [x] `./secs/__init__.py` (Nick)
- [x] `./soho/__init__.py` (Jiashu)
- [x] `./solo/__init__.py` (Jiashu)
- [x] `./st5/__init__.py` (Cindy)
- [x] `./stereo/__init__.py` (Cindy)
- [x] `./swarm/__init__.py` (Sasha)
- [x] `./twins/__init__.py` (Jim L)
- [x] `./ulysses/__init__.py` (Jim L)
- [x] `./wind/__init__.py` (Jim L)

**Comment by jameswilburlewis** [comment]
ChatGPT helped me write a shell script to split an __init__.py file into one file per function.  It should copy any preamble (imports etc) into each of the new files it makes.  

I haven't vetted it beyond trying it on an example or two -- PLEASE don't risk doing this in your live development directory!  Instead, make a new directory somewhere like /tmp/refactor, then copy the code block below, and paste it into a file /tmp/refactor/refactor_init.sh   

Don't forget to make it executable with "chmod +x refactor.sh"

Then, cd into /tmp/refactor, which should have the script in it.  Copy the __init__.py file you want to work on into that directory.  Then,

./refactor_init.sh

This should create several new .py files.   You can copy these back to the original directory and add them to git, then proceed with the rest of the modifications for that directory, as described in the instructions above.

When you're ready to move on to a new directory, delete everything except the refactor_init.sh script, and start fresh with a new __init__.py file.


```
#!/bin/bash

# Directory containing the original __init__.py files
INIT_DIR="."

# Directory to store the refactored modules
REFAC_DIR="."

# Create the refactored directory if it does not exist
mkdir -p "$REFAC_DIR"

# Function to extract functions and write to individual files
extract_functions() {
    local file="$1"
    local module_dir="$2"
    local func_name=""
    local in_function=0
    local preamble=()
    local func_content=()

    while IFS= read -r line; do
        if [[ "$line" =~ ^def\ ([a-zA-Z0-9_]+)\( ]]; then
            if [[ -z "$func_name" ]]; then
                # This is the first function, add preamble to each function file
                in_function=1
                func_content=("${preamble[@]}") # Start with the preamble
            fi
            if [[ "$in_function" -eq 1 && -n "$func_name" ]]; then
                # Write function to file
                printf "%s\n" "${func_content[@]}" > "$module_dir/${func_name}.py"
                func_content=("${preamble[@]}") # Reset array with preamble
            fi
            in_function=1
            func_name="${BASH_REMATCH[1]}"
            func_content+=("$line")
        elif [[ "$in_function" -eq 1 ]]; then
            func_content+=("$line")
        else
            # Collect preamble lines
            preamble+=("$line")
        fi
    done < "$file"

    if [[ "$in_function" -eq 1 && -n "$func_name" ]]; then
        # Write the last function to file
        printf "%s\n" "${func_content[@]}" > "$module_dir/${func_name}.py"
    fi
}

# Process each __init__.py file
for init_file in "$INIT_DIR"/__init__.py; do
    module_name=$(basename "$(dirname "$init_file")")
    module_refac_dir="$REFAC_DIR/$module_name"
    mkdir -p "$module_refac_dir"
    extract_functions "$init_file" "$module_refac_dir"
done

```

**Comment by jameswilburlewis** [comment]
FYI, if you want to see how it went for the akebono directory, check the commits for July 24 here: https://github.com/spedas/pyspedas/commits/master/pyspedas/akebono

A few notes:

I've already added support for force_download for several directories, including akebono.  Check the whole argument list before adding it, in case it's already there.

This was one of the missions that loads tplot variables from CSV files, so adding prefix and suffix support took a little more effort than just passing the parameters to cdf_to_tplot.   Also, there was already some application of prefixes to put the mission name and/or instrument in the tplot variables, so some logic was needed to merge the user-requested prefix with the ones that were being used internally.

Finally, it occurred to me that even if we provide prefix='' and suffix='' as defaults, we should check if the user happened to specify them as None (which would cause problems later in the code when doing string manipulations).  

It might be a good idea to put something like:

```
if prefix is None:
   prefix=''

if suffix is None:
   suffix=''

```
in the master load routine, or anywhere where you're actually using the values and not just passing them down a chain of function calls.

cdf_to_tplot doesn't currently check for that case!  (I'll ago ahead and add it there, but better safe than sorry...)

**Comment by nickssl** [comment]
I'd like to add two tips that may be useful and can simplify a lot of duplicated code:

1. Alias. In some __init__.py files there is a function which is exactly the same as the load() function but has a different name (for example, data) and simply calls the load() function with exactly the same parameters. In this case we have an alias, and we can replace the data() function (and all the documentation etc), with just an equality like this:

``
data = load
``

For example, in GOES __init__.py, we have this:
``
orbit = load_orbit
``

2. Partial. In some other __init__.py functions we have a function with an instrument name, which calls the load() function setting just one parameter, usually the instrument, and all other parameters are the same. In this case, we can replace that function with a "partial". For an example, see again the GOES __init__.py file:

``
from functools import partial
fgm = partial(load, instrument="fgm")
eps = partial(load, instrument="eps")
epead = partial(load, instrument="epead")
maged = partial(load, instrument="maged")
``

In both cases, we do not need any duplicate documentation. And any updates to load() are automatically applied to all alias and partial functions, without having to manually add any new parameters (like force_download, prefix, etc).

**Comment by jameswilburlewis** [comment]
Using partial(), or other wrappers from the functools library, has a few significant disadvantages.  You lose the ability to have argument autocompletion or type hint checking -- all you get is the generic (**args, **kwargs).  Also, it won't show up in a libs() call. and help() just shows the information for the partial object:

```
help(pyspedas.goes.epead)
Help on partial object:
class partial(builtins.object)
 |  partial(func, *args, **keywords) - new function with partial application
 |  of the given arguments and keywords.
 |  
 |  Methods defined here:
 |  
 |  __call__(self, /, *args, **kwargs)
 |      Call self as a function.
 |  
 |  __delattr__(self, name, /)
 |      Implement delattr(self, name).
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __reduce__(...)
 |      Helper for pickle.
 |  
 |  __repr__(self, /)
 |      Return repr(self).



```

Aliases (e.g. `orbit = load_orbit') seem OK in these respects.  But until we can find a workaround for the libs() and help() issues, I would discourage the use of partial() or wrappers for load routines.  We absolutely need them to be discoverable and fully documented under their own names.

**Comment by nickssl** [comment]
For help() you need to add ".func". For example:

<pre>
help(pyspedas.goes.epead.func)
</pre>

Perhaps we can add our own pyspedas.help() function, and then the user would not need to add ".func". For example:

<pre>
def help(partial_func):
    """Fetch help for the original function from a partial."""
    if isinstance(partial_func, functools.partial):
        help(partial_func.func)
    else:
        help(partial_func)
</pre>

I think we can modify lib() to search for partial functions, too.

**Comment by jameswilburlewis** [comment]
functools.update_wrapper() seems to help with the help() issue:

With this in goes/__init__.py:

```
epead = partial(load, instrument="epead")
update_wrapper(epead,load)

```
we get this:


```
help(pyspedas.goes.epead)
Help on partial in module pyspedas.goes.load:
load = functools.partial(<function load at 0x29c3cfaf0>, instrument='epead')
    Load GOES L2 data.
    
    Parameters
    ----------
    trange : list of str
        Time range of interest ['YYYY-MM-DD', 'YYYY-MM-DD'] or to specify more or less than a day
        ['YYYY-MM-DD/hh:mm:ss', 'YYYY-MM-DD/hh:mm:ss'].
    probe : str, int, or list of str/int
        GOES spacecraft number(s), e.g., probe=15.
    instrument : str or list of str
        Name of the instrument. For GOES 8-15: 'fgm', 'eps', 'epead', 'maged', 'magpd', 'hepad', 'xrs'.
        For GOES-R 16-18: 'euvs', 'xrs', 'mag', 'mpsh', 'sgps'.
...etc...

```

**Comment by nickssl** [comment]
Autocomplete works with partial functions in visual studio code. I am not sure about other tools. 

![image](https://github.com/user-attachments/assets/db8cbd20-5720-49bd-81b0-9ed3caa4a05b)

**Comment by jameswilburlewis** [comment]
For PyCharm, there's been a long-standing open issue on code completion with partials: https://youtrack.jetbrains.com/issue/PY-25698

There's an interesting snippet of code in the comments that lets you define partials, and have them work with PyCharm's autocompletion.  I'm not sure exactly what the magic is that makes it work, but with this in `goes/__init__,py`:

```
from typing import TypeVar

T = TypeVar('T')

def better_partial(func: T, *args, **kwargs) -> T:
    """
    Behaves the same as functools.partial, but works with idea's type hinting.
    @see https://youtrack.jetbrains.com/issue/PY-25698/No-proper-completion-or-parameter-info-for-partially-applied-parameters-of-functools.partial
    """
    return partial(func, *args, **kwargs)

```

```
maged = better_partial(load, instrument="maged")
update_wrapper(maged,load)

```

you can hover over a call to maged and see the actual arguments.  The update_wrapper call is still necessary to make it work with help().   If we can just get libs() to work with it, I think we might have a solution!

**Comment by nickssl** [comment]
By the way, Visual Studio Code (vscode) is a really great tool! And it is free! 

I think in the future IDL will also work on vscode. They already have an extension. When I tested it, it worked fine for simple things but not for the full IDL spedas (which is understandable). 

https://www.nv5geospatialsoftware.com/Learn/Videos/Video-Detail/reimagine-the-way-you-program-with-idl-for-vscode

**Comment by jameswilburlewis** [comment]
I've added `better_partial()` to a new file, utilities/pyspedas_functools.py.

Here's what `goes/__init__.py` looks like now:

```
from .load import load, loadr
from .load_orbit import load_orbit
from functools import partial, update_wrapper
from pyspedas.utilities.pyspedas_functools import better_partial

# Define alias to the load function
orbit = load_orbit

# Define partial wrappers for other load routines, fixing the instrument parameter
# 'better_partial' works better with PyCharm autocompletion than functools.partial
# update_wrapper() is necessary for help() to show info for the wrapped function,
# rather than the partial() object.

fgm = better_partial(load, instrument="fgm")
update_wrapper(fgm, load)
eps = better_partial(load, instrument="eps")
update_wrapper(eps, load)
epead = better_partial(load, instrument="epead")
update_wrapper(epead,load)
maged = better_partial(load, instrument="maged")
update_wrapper(maged,load)
magpd = better_partial(load, instrument="magpd")
update_wrapper(magpd, load)
hepad = better_partial(load, instrument="hepad")
update_wrapper(hepad, load)
xrs = better_partial(load, instrument="xrs")
update_wrapper(xrs, load)
euvs = better_partial(load, instrument="euvs")
update_wrapper(euvs, load)
mag = better_partial(load, instrument="mag")
update_wrapper(mag, load)
mpsh = better_partial(load, instrument="mpsh")
update_wrapper(mpsh, load)
sgps = better_partial(load, instrument="sgps")
update_wrapper(sgps, load)


```

I've updated libs.py with some code suggested by Nick (and GPT-4) over in the libs() thread:
https://github.com/spedas/pyspedas/issues/947

This approach seems to work acceptably well with the updated libs() command, Pycharm autocomplete, sphinx (readthedocs), and help().

So I think this is now a viable option for defining a suite of load routines, all derived from the same master load routine with changing 'instrument' parameters.

But for the purpose of this task, let's stay focused on refactoring the `__init__.py` files, and leave tweaks like this for the future.

**Comment by jiashuwu89** [comment]
PSP/fields.py has:

```
if suffix:
        suffix = '_' + suffix
```

When users specify a suffix or prefix, should we add an underscore ('_') automatically?

**Comment by jameswilburlewis** [comment]
No, we don't do that anywhere else, so I think that bit of code should be removed.
