### ISSUE TITLE
Add option to use HTTPS rather than FTP for downloading from gfz-potsdam.de

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#948]
test_load_kp_data_2014 and test_load_kp_data_2024 both started failing today, with:

```
26-Jul-24 13:31:36: 530 Login incorrect.
26-Jul-24 13:31:36: No files found.
26-Jul-24 13:31:36: Loading geomagnetic index data from ftp.gfz-potsdam.de/pub/home/obs/kp-ap/wdc/yearly/

Failure
Traceback (most recent call last):
  File "/Users/jwl/PycharmProjects/pyspedas/pyspedas/noaa/tests/tests.py", line 60, in test_load_kp_data_2014_gfz
    self.assertTrue('Kp' in kp_vars)
AssertionError: False is not true


```

It could be a transient error, or perhaps a policy change?

**Comment by nickssl** [comment]
I cannot connect using an ftp client, either.

**Comment by jameswilburlewis** [comment]
It looks like the FTP site is back in operation.  They are still advertising the FTP URLs, so I guess this was some sort of configuration error rather than a policy change.

But it looks like this data is now available via HTTPS:

https://kp.gfz-potsdam.de/en/data

There are URLs to load the entire dataset since 1932 in a single file, and a simple API to download specific time ranges.

It might be good to change our code to use the HTTPS service -- it's a lot easier to troubleshoot if we don't have to deal with an FTP client, authentication issues, etc.

**Comment by nickssl** [comment]
I have now added HTTPS downloads from GFZ and made it the default for GFZ (since HTTPS downloads are usually more reliable than FTP downloads).
