### ISSUE TITLE
tplot_copy produces unuseable variables

### ISSUE THREAD

**Issue by bpwrs** [spedas/pyspedas#957]
May be more appropriate for pytplot specifc page but posting here.

Ran into this issue when using tplot_copy to rename MMS FEEPS spectrogram data. Basically put tplot_copy successfully copies the y (1 dimensional time) and the x (2 dimensional values) but does not copy the  v data (1 dimensional spectrogram bins). Therefore, the new variable is unplottable as tplot does not know how to handle the 1D time vs 2D values. I got around the bug by renaming the values using pytplot.store_data which works as I expected tplot_copy to work.

**Comment by jameswilburlewis** [comment]
Thanks for letting us know about the problem!  It's fixed in pyspedas-1.5.17/pytplot-mpl-temp-2.2.39, both released to pypi.org this morning.
