### ISSUE TITLE
No module named 'bokeh.plotting.figure'

### ISSUE THREAD

**Issue by t45166532** [spedas/pyspedas#963]
The line:
`import pyspedas`

produces the following error

> {
> 	"name": "ModuleNotFoundError",
> 	"message": "No module named 'bokeh.plotting.figure'",
> 	"stack": "---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> Cell In[11], line 1
> ----> 1 import pyspedas
> 
> File c:\\Users\\name_omitted\\Documents\\analysis\\02_07_2024---pyspeedas\\.venv\\Lib\\site-packages\\pyspedas\\__init__.py:5
>       1 # Import pyspedas tools into pyspedas namespace
>       2 # These are imported as a convenience for pyspedas users.  For internal pyspedas development, it is
>       3 # probably best to keep using the fully qualified module names.
> ----> 5 from .analysis.avg_data import avg_data
>       6 from .analysis.deriv_data import deriv_data
>       7 from .analysis.tvectot import tvectot
> 
> File c:\\Users\\name_omitted\\Documents\\analysis\\02_07_2024---pyspeedas\\.venv\\Lib\\site-packages\\pyspedas\\analysis\\avg_data.py:11
>       9 import logging
>      10 import numpy as np
> ---> 11 from pytplot import store_data, get_data, tnames, time_float
>      14 def avg_data(names, trange=[], res=None, width=None,
>      15              newname=None, new_names=None, suffix=None, overwrite=False):
>      16     \"\"\"
>      17     Get a new tplot variable with averaged data.
>      18 
>    (...)
>      50 
>      51     \"\"\"
> 
> File c:\\Users\\name_omitted\\Documents\\analysis\\02_07_2024---pyspeedas\\.venv\\Lib\\site-packages\\pytplot\\__init__.py:7
>       1 # Copyright 2018 Regents of the University of Colorado. All Rights Reserved.
>       2 # Released under the MIT license.
>       3 # This software was developed at the University of Colorado's Laboratory for Atmospheric and Space Physics.
>       4 # Verify current version before use at: https://github.com/MAVENSDC/PyTplot
>       6 from _collections import OrderedDict
> ----> 7 from . import HTMLPlotter
>       8 import os
>       9 import sys
> 
> File c:\\Users\\name_omitted\\Documents\\analysis\\02_07_2024---pyspeedas\\.venv\\Lib\\site-packages\\pytplot\\HTMLPlotter\\__init__.py:6
>       1 # Copyright 2018 Regents of the University of Colorado. All Rights Reserved.
>       2 # Released under the MIT license.
>       3 # This software was developed at the University of Colorado's Laboratory for Atmospheric and Space Physics.
>       4 # Verify current version before use at: https://github.com/MAVENSDC/PyTplot
> ----> 6 from .TVarFigure1D import TVarFigure1D
>       7 from .TVarFigureMap import TVarFigureMap
>       8 from .TVarFigureAlt import TVarFigureAlt
> 
> File c:\\Users\\name_omitted\\Documents\\analysis\\02_07_2024---pyspeedas\\.venv\\Lib\\site-packages\\pytplot\\HTMLPlotter\\TVarFigure1D.py:8
>       6 from __future__ import division
>       7 import numpy as np
> ----> 8 from bokeh.plotting.figure import Figure
>       9 from bokeh.models import (ColumnDataSource, DatetimeAxis, HoverTool, 
>      10                           Range1d, Span, Title, Legend, BoxAnnotation)
>      11 from bokeh.models.glyphs import Line
> 
> ModuleNotFoundError: No module named 'bokeh.plotting.figure'"
> }

Checking my packages list, I see bokeh is there:

> Package            Version
> ------------------ ------------------
> astropy            6.1.2
> astropy-iers-data  0.2024.7.29.0.32.7
> asttokens          2.4.1
> blosc2             2.7.1
> bokeh              3.5.1
> cdasws             1.8.4
> cdflib             1.3.1
> certifi            2024.7.4
> cftime             1.6.4
> charset-normalizer 3.3.2
> colorama           0.4.6
> comm               0.2.2
> contourpy          1.2.1
> cycler             0.12.1
> debugpy            1.8.2
> decorator          5.1.1
> executing          2.0.1
> fonttools          4.53.1
> geopack            1.0.10
> hapiclient         0.2.6
> idna               3.7
> ipykernel          6.29.5
> ipython            8.26.0
> isodate            0.6.1
> jedi               0.19.1
> Jinja2             3.1.4
> joblib             1.4.2
> jupyter_client     8.6.2
> jupyter_core       5.7.2
> kiwisolver         1.4.5
> MarkupSafe         2.1.5
> matplotlib         3.9.1
> matplotlib-inline  0.1.7
> msgpack            1.0.8
> ndindex            1.8
> nest-asyncio       1.6.0
> netCDF4            1.7.1.post1
> numexpr            2.10.1
> numpy              2.0.1
> packaging          24.1
> pandas             2.2.2
> parso              0.8.4
> pillow             10.4.0
> pip                24.2
> platformdirs       4.2.2
> prompt_toolkit     3.0.47
> psutil             6.0.0
> pure_eval          0.2.3
> py-cpuinfo         9.0.0
> pyerfa             2.0.1.4
> Pygments           2.18.0
> pyparsing          3.1.2
> PyQt5              5.15.11
> PyQt5-Qt5          5.15.2
> PyQt5_sip          12.15.0
> pyqtgraph          0.13.7
> PyQtWebEngine      5.15.7
> PyQtWebEngine-Qt5  5.15.2
> pyspedas           1.5.16
> python-dateutil    2.9.0.post0
> pytplot            1.7.28
> pytplot-mpl-temp   2.2.38
> pytz               2024.1
> PyWavelets         1.6.0
> pywin32            306
> PyYAML             6.0.1
> pyzmq              26.0.3
> requests           2.32.3
> scipy              1.14.0
> six                1.16.0
> stack-data         0.6.3
> tables             3.9.2
> tornado            6.4.1
> tqdm               4.66.4
> traitlets          5.14.3
> tzdata             2024.1
> urllib3            2.2.2
> viresclient        0.11.8
> wcwidth            0.2.13
> xarray             2024.7.0
> xyzservices        2024.6.0

Trying to run this in the python stand alone rather than vscode as a notebook doesn't seem to help

>(.venv) C:\Users\name_omitted\Documents\analysis\02_07_2024---pyspeedas>python
Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyspedas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\name_omitted\Documents\analysis\02_07_2024---pyspeedas\.venv\Lib\site-packages\pyspedas\__init__.py", line 5, in <module>
    from .analysis.avg_data import avg_data
  File "C:\Users\name_omitted\Documents\analysis\02_07_2024---pyspeedas\.venv\Lib\site-packages\pyspedas\analysis\avg_data.py", line 11, in <module>
    from pytplot import store_data, get_data, tnames, time_float
  File "C:\Users\name_omitted\Documents\analysis\02_07_2024---pyspeedas\.venv\Lib\site-packages\pytplot\__init__.py", line 7, in <module>
    from . import HTMLPlotter
  File "C:\Users\name_omitted\Documents\analysis\02_07_2024---pyspeedas\.venv\Lib\site-packages\pytplot\HTMLPlotter\__init__.py", line 6, in <module>
    from .TVarFigure1D import TVarFigure1D
  File "C:\Users\name_omitted\Documents\analysis\02_07_2024---pyspeedas\.venv\Lib\site-packages\pytplot\HTMLPlotter\TVarFigure1D.py", line 8, in <module>
    from bokeh.plotting.figure import Figure
ModuleNotFoundError: No module named 'bokeh.plotting.figure'

Double checking that  it's in the pip list from command line
> .venv) C:\Users\name_omitted\Documents\analysis\02_07_2024---pyspeedas>pip list
> Package            Version
> ------------------ ------------------
> astropy            6.1.2
> astropy-iers-data  0.2024.7.29.0.32.7
> asttokens          2.4.1
> blosc2             2.7.1
> bokeh              3.5.1
> cdasws             1.8.4
> cdflib             1.3.1
> certifi            2024.7.4
> cftime             1.6.4
> charset-normalizer 3.3.2
> colorama           0.4.6
> comm               0.2.2
> contourpy          1.2.1
> cycler             0.12.1
> debugpy            1.8.2
> decorator          5.1.1
> executing          2.0.1
> fonttools          4.53.1
> geopack            1.0.10
> hapiclient         0.2.6
> idna               3.7
> ipykernel          6.29.5
> ipython            8.26.0
> isodate            0.6.1
> jedi               0.19.1
> Jinja2             3.1.4
> joblib             1.4.2
> jupyter_client     8.6.2
> jupyter_core       5.7.2
> kiwisolver         1.4.5
> MarkupSafe         2.1.5
> matplotlib         3.9.1
> matplotlib-inline  0.1.7
> msgpack            1.0.8
> ndindex            1.8
> nest-asyncio       1.6.0
> netCDF4            1.7.1.post1
> numexpr            2.10.1
> numpy              2.0.1
> packaging          24.1
> pandas             2.2.2
> parso              0.8.4
> pillow             10.4.0
> pip                24.2
> platformdirs       4.2.2
> prompt_toolkit     3.0.47
> psutil             6.0.0
> pure_eval          0.2.3
> py-cpuinfo         9.0.0
> pyerfa             2.0.1.4
> Pygments           2.18.0
> pyparsing          3.1.2
> PyQt5              5.15.11
> PyQt5-Qt5          5.15.2
> PyQt5_sip          12.15.0
> pyqtgraph          0.13.7
> PyQtWebEngine      5.15.7
> PyQtWebEngine-Qt5  5.15.2
> pyspedas           1.5.16
> python-dateutil    2.9.0.post0
> pytplot            1.7.28
> pytplot-mpl-temp   2.2.38
> pytz               2024.1
> PyWavelets         1.6.0
> pywin32            306
> PyYAML             6.0.1
> pyzmq              26.0.3
> requests           2.32.3
> scipy              1.14.0
> six                1.16.0
> stack-data         0.6.3
> tables             3.9.2
> tornado            6.4.1
> tqdm               4.66.4
> traitlets          5.14.3
> tzdata             2024.1
> urllib3            2.2.2
> viresclient        0.11.8
> wcwidth            0.2.13
> xarray             2024.7.0
> xyzservices        2024.6.0

Any ideas?

**Comment by jameswilburlewis** [comment]
I think the problem is that you have both the original "pytplot" and the current "pytplot-mpl-temp" packages in your environment:

```
pytplot 1.7.28
pytplot-mpl-temp 2.2.38
```

 pytplot-mpl-temp is the one required by pyspedas, while the original pytplot is no longer compatible.  

To fix this, you'll need to uninstall the original pytplot:

`pip uninstall pytplot`

then reinstall pytplot-mpl-temp:

`pip install pytplot-mpl-temp`

That should get rid of the error on `import pyspedas`.

**Comment by t45166532** [comment]
Well, atleast now i'm getting a different error

> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> Cell In[15], [line 1](vscode-notebook-cell:?execution_count=15&line=1)
> ----> [1](vscode-notebook-cell:?execution_count=15&line=1) import pyspedas
> 
> File c:\Users\terry.price\Documents\analysis\02_07_2024---pyspeedas\.venv\Lib\site-packages\pyspedas\__init__.py:5
>       [1](file:///C:/Users/terry.price/Documents/analysis/02_07_2024---pyspeedas/.venv/Lib/site-packages/pyspedas/__init__.py:1) # Import pyspedas tools into pyspedas namespace
>       [2](file:///C:/Users/terry.price/Documents/analysis/02_07_2024---pyspeedas/.venv/Lib/site-packages/pyspedas/__init__.py:2) # These are imported as a convenience for pyspedas users.  For internal pyspedas development, it is
>       [3](file:///C:/Users/terry.price/Documents/analysis/02_07_2024---pyspeedas/.venv/Lib/site-packages/pyspedas/__init__.py:3) # probably best to keep using the fully qualified module names.
> ----> [5](file:///C:/Users/terry.price/Documents/analysis/02_07_2024---pyspeedas/.venv/Lib/site-packages/pyspedas/__init__.py:5) from .analysis.avg_data import avg_data
>       [6](file:///C:/Users/terry.price/Documents/analysis/02_07_2024---pyspeedas/.venv/Lib/site-packages/pyspedas/__init__.py:6) from .analysis.deriv_data import deriv_data
>       [7](file:///C:/Users/terry.price/Documents/analysis/02_07_2024---pyspeedas/.venv/Lib/site-packages/pyspedas/__init__.py:7) from .analysis.tvectot import tvectot
> 
> File c:\Users\terry.price\Documents\analysis\02_07_2024---pyspeedas\.venv\Lib\site-packages\pyspedas\analysis\avg_data.py:11
>       [9](file:///C:/Users/terry.price/Documents/analysis/02_07_2024---pyspeedas/.venv/Lib/site-packages/pyspedas/analysis/avg_data.py:9) import logging
>      [10](file:///C:/Users/terry.price/Documents/analysis/02_07_2024---pyspeedas/.venv/Lib/site-packages/pyspedas/analysis/avg_data.py:10) import numpy as np
> ---> [11](file:///C:/Users/terry.price/Documents/analysis/02_07_2024---pyspeedas/.venv/Lib/site-packages/pyspedas/analysis/avg_data.py:11) from pytplot import store_data, get_data, tnames, time_float
>      [14](file:///C:/Users/terry.price/Documents/analysis/02_07_2024---pyspeedas/.venv/Lib/site-packages/pyspedas/analysis/avg_data.py:14) def avg_data(names, trange=[], res=None, width=None,
>      [15](file:///C:/Users/terry.price/Documents/analysis/02_07_2024---pyspeedas/.venv/Lib/site-packages/pyspedas/analysis/avg_data.py:15)              newname=None, new_names=None, suffix=None, overwrite=False):
>      [16](file:///C:/Users/terry.price/Documents/analysis/02_07_2024---pyspeedas/.venv/Lib/site-packages/pyspedas/analysis/avg_data.py:16)     """
>      [17](file:///C:/Users/terry.price/Documents/analysis/02_07_2024---pyspeedas/.venv/Lib/site-packages/pyspedas/analysis/avg_data.py:17)     Get a new tplot variable with averaged data.
>      [18](file:///C:/Users/terry.price/Documents/analysis/02_07_2024---pyspeedas/.venv/Lib/site-packages/pyspedas/analysis/avg_data.py:18) 
>    (...)
>      [50](file:///C:/Users/terry.price/Documents/analysis/02_07_2024---pyspeedas/.venv/Lib/site-packages/pyspedas/analysis/avg_data.py:50) 
>      [51](file:///C:/Users/terry.price/Documents/analysis/02_07_2024---pyspeedas/.venv/Lib/site-packages/pyspedas/analysis/avg_data.py:51)     """
> 
> File c:\Users\terry.price\Documents\analysis\02_07_2024---pyspeedas\.venv\Lib\site-packages\pytplot\tnames.py:2
>       [1](file:///C:/Users/terry.price/Documents/analysis/02_07_2024---pyspeedas/.venv/Lib/site-packages/pytplot/tnames.py:1) import fnmatch, re, logging
> ----> [2](file:///C:/Users/terry.price/Documents/analysis/02_07_2024---pyspeedas/.venv/Lib/site-packages/pytplot/tnames.py:2) from pytplot import tplot_names
>       [5](file:///C:/Users/terry.price/Documents/analysis/02_07_2024---pyspeedas/.venv/Lib/site-packages/pytplot/tnames.py:5) def tnames(pattern=None, regex=None):
>       [6](file:///C:/Users/terry.price/Documents/analysis/02_07_2024---pyspeedas/.venv/Lib/site-packages/pytplot/tnames.py:6)     """
>       [7](file:///C:/Users/terry.price/Documents/analysis/02_07_2024---pyspeedas/.venv/Lib/site-packages/pytplot/tnames.py:7)     Find tplot names matching a wildcard pattern.
>       [8](file:///C:/Users/terry.price/Documents/analysis/02_07_2024---pyspeedas/.venv/Lib/site-packages/pytplot/tnames.py:8) 
>    (...)
>      [33](file:///C:/Users/terry.price/Documents/analysis/02_07_2024---pyspeedas/.venv/Lib/site-packages/pytplot/tnames.py:33)         >>> pytplot.tnames('th?_fgs_gsm')
>      [34](file:///C:/Users/terry.price/Documents/analysis/02_07_2024---pyspeedas/.venv/Lib/site-packages/pytplot/tnames.py:34)     """
> 
> ImportError: cannot import name 'tplot_names' from 'pytplot' (unknown location)


Here is my package list

> Package            Version
> ------------------ ------------------
> astropy            6.1.2
> astropy-iers-data  0.2024.7.29.0.32.7
> asttokens          2.4.1
> blosc2             2.7.1
> bokeh              3.5.1
> cdasws             1.8.4
> cdflib             1.3.1
> certifi            2024.7.4
> cftime             1.6.4
> charset-normalizer 3.3.2
> colorama           0.4.6
> comm               0.2.2
> contourpy          1.2.1
> cycler             0.12.1
> debugpy            1.8.2
> decorator          5.1.1
> executing          2.0.1
> fonttools          4.53.1
> geopack            1.0.10
> h5py               3.11.0
> hapiclient         0.2.6
> idna               3.7
> ipykernel          6.29.5
> ipython            8.26.0
> isodate            0.6.1
> jedi               0.19.1
> Jinja2             3.1.4
> joblib             1.4.2
> jupyter_client     8.6.2
> jupyter_core       5.7.2
> kiwisolver         1.4.5
> MarkupSafe         2.1.5
> matplotlib         3.9.1
> matplotlib-inline  0.1.7
> msgpack            1.0.8
> ndindex            1.8
> nest-asyncio       1.6.0
> netCDF4            1.7.1.post1
> numexpr            2.10.1
> numpy              2.0.1
> packaging          24.1
> pandas             2.2.2
> parso              0.8.4
> pillow             10.4.0
> pip                24.2
> platformdirs       4.2.2
> prompt_toolkit     3.0.47
> psutil             6.0.0
> pure_eval          0.2.3
> py-cpuinfo         9.0.0
> pyerfa             2.0.1.4
> Pygments           2.18.0
> pyparsing          3.1.2
> PyQt5              5.15.11
> PyQt5-Qt5          5.15.2
> PyQt5_sip          12.15.0
> pyqtgraph          0.13.7
> PyQtWebEngine      5.15.7
> PyQtWebEngine-Qt5  5.15.2
> pyspedas           1.5.16
> python-dateutil    2.9.0.post0
> pytplot-mpl-temp   2.2.38
> pytz               2024.1
> PyWavelets         1.6.0
> pywin32            306
> PyYAML             6.0.1
> pyzmq              26.0.3
> requests           2.32.3
> scipy              1.14.0
> six                1.16.0
> spacepy            0.6.0
> stack-data         0.6.3
> tables             3.9.2
> tornado            6.4.1
> tqdm               4.66.4
> traitlets          5.14.3
> tzdata             2024.1
> urllib3            2.2.2
> viresclient        0.11.8
> wcwidth            0.2.13
> xarray             2024.7.0
> xyzservices        2024.6.0
>

**Comment by jameswilburlewis** [comment]
If you're still getting an error, I guess the first step would be to exit/restart your python interpreter if you haven't done so already. It might be still looking in the old location for your pytplot installation.

If that doesn't fix the issue, it's possible something might have gone wrong with the uninstall of old pytplot or reinstall of pytplot-mpl-temp.  Maybe a more forcible method will work:  find the directory where the packages are installed for your environment (possibly something like pyspedas/venv/lib/python3.9/site-packages), then remove anything with "pytplot" in the directory name.  Then try "pip install pytplot-mpl-temp" again, restart your interpreter, and hopefully you'll be able to import pyspedas and pytplot without errors.
