### ISSUE TITLE
Improvement in the `rbsp` module code

### ISSUE THREAD

**Issue by xandrd** [spedas/pyspedas#981]
During refactoring, I noticed several issues with the code in the `rbsp` module. I suggest the following improvements, which will be implemented in the branch `rbsp_code_improvement`, a branch of `init_refactor`:

1. **Refactor `load` function patterns to use f-strings:**
   The `pathformat` string could be refactored into an f-string for better readability:
   https://github.com/spedas/pyspedas/blob/db089519f4dadb1b888396887a3c0d9436d4866d/pyspedas/rbsp/load.py#L127

   **Suggestion:**
   ```python
   pathformat = f'rbsp{prb}/{level}/{instrument}/{datatype}/%Y/rbsp-{prb}_{datatype}_{instrument}-{level}_%Y%m%d_v*.cdf'
   ```

2. **Check for `files` in the `load` function:**
   The check for `files` could be simplified. If `files` is not `None` or empty, the following code appends them to `out_files`:
   https://github.com/spedas/pyspedas/blob/db089519f4dadb1b888396887a3c0d9436d4866d/pyspedas/rbsp/load.py#L166-L168

   **Suggestion:**
   ```python
   if files:
       out_files.extend(files)
   ```

3. **Redundant condition check:**
   There is a condition that seems to be redundant:
   https://github.com/spedas/pyspedas/blob/db089519f4dadb1b888396887a3c0d9436d4866d/pyspedas/rbsp/load.py#L182-L183

   **Question:** Should this condition be deleted?

4. **Potential `TypeError` in handling `tvars`:**
   The code could potentially lead to a `TypeError` because `tvars` is expected to be a dictionary. Instead of assigning it directly, `tvars` should be updated with the contents of `tvars_o`:
   https://github.com/spedas/pyspedas/blob/db089519f4dadb1b888396887a3c0d9436d4866d/pyspedas/rbsp/load.py#L175

   **Suggestion:**
   ```python
   tvars.update(tvars_o)
   ```

5. **`rps` function default value for `get_support_data`:**
   Currently, the `rps` function has `get_support_data=True` by default, but the documentation does not reflect this. 
   
   **Question:**  Should the default be changed to `get_support_data=False` to match the documentation, or should the documentation be updated to match the current behavior? Changing the default could lead to a change in behavior.

6. **Potential issue with condition in `rbspice` function:**
   There might be a wrong condition in the `rbspice` function:
   https://github.com/spedas/pyspedas/blob/db089519f4dadb1b888396887a3c0d9436d4866d/pyspedas/rbsp/rbspice.py#L120-L127

   **Should the following code be used instead?**
   ```python
   sp_avg_vars = rbsp_rbspice_spin_avg(probe=prb, datatype=datatype, level=level)
   if sp_avg_vars:
       tvars.extend(sp_avg_vars)
   ```

**Comment by xandrd** [comment]
@jim, `rps` data requires `get_support_data=True` to pass this test:
https://github.com/spedas/pyspedas/blob/fdd49a71abc71c40d0a21c50343d36d251579aa5/pyspedas/rbsp/tests/tests.py#L104-L108

Specifically:
```python
rps_vars = pyspedas.rbsp.rps(datatype='rps') 
self.assertTrue(data_exists('FPDU_Energy'))
```

Should I change the test to:
```python
rps_vars = pyspedas.rbsp.rps(datatype='rps', get_support_data=True) 
self.assertTrue(data_exists('FPDU_Energy'))
```

Or should `get_support_data=True` by default? It is relevant to my **question 5**.

**Comment by jameswilburlewis** [comment]
1) fstrings: sounds good!
2) empty list for files: suggestion looks good
3) notplot check:  I think this should be left as-is, so it won't attempt time clipping even if time_clip is True
4) tvars.update() instead of assignment: suggestion looks good
5) rps() and get_support_data:  Leave code as-is, update documentation
6) omni_vars: condition:  Suggestion looks correct

**Comment by xandrd** [comment]
Hi @jameswilburlewis,  in regards to 3 - I think `time_clip` should be applied if it set to `True`, regardless of the `nptplot` flag. Otherwise it is a confusing behavior of the function. I would even call it a bug. No?

**Comment by jameswilburlewis** [comment]
But time_clip would require the creation of tplot variables.  I guess you could add a warning if both time_clip and notplot are set, in which case I'd prefer to honor notplot rather than time_clip.

**Comment by xandrd** [comment]
I see, the I assume `tclip` works only with pytplot variables. I will remove this change, run the tests one more time and push the update.

**Comment by xandrd** [comment]
All tests are passed I created a pull request.

**Comment by jameswilburlewis** [comment]
Looks good, both PRs have been merged!
